### PR TITLE
Dnsperfgo image should be build in isolated environment

### LINKED ISSUE #2001: Dnsperfgo image should be build in isolated environment
Dnsperfgo is currently build on host machine and not in isolated environment: https://github.com/kubernetes/perf-tests/blob/edbd49ced99afdc71555a3d028cfbb8f46490f43/dns/dnsperfgo/Makefile#L13
then it's copied to image: https://github.com/kubernetes/perf-tests/blob/edbd49ced99afdc71555a3d028cfbb8f46490f43/dns/dnsperfgo/Dockerfile#L7

We should build binary in isolated env, just like we do for sleep image: https://github.com/kubernetes/perf-tests/blob/edbd49ced99afdc71555a3d028cfbb8f46490f43/util-images/sleep/Dockerfile#L1

/good-first-issue

### PR DESCRIPTION
**Pull request by uroy-personal**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Dnsperfgo image should be build in isolated environment

Fixes #2001

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by marseel** [comment]
I've tried to build image with your change and looks like `make build` fails with error:
```
Step 5/12 : RUN CGO_ENABLED=1 go build -o dnsperfcgo main.go
 ---> Running in c113e8d69e75
go: downloading golang.org/x/net v0.0.0-20200625001655-4c5254603344
# command-line-arguments
./main.go:72:25: undefined: startMetricsServer
./main.go:73:2: undefined: registerMetrics
./main.go:144:3: undefined: dnsErrorsCounter
./main.go:148:3: undefined: dnsTimeoutsCounter
./main.go:151:2: undefined: dnsLookupsCounter
./main.go:163:3: undefined: dnsLatency
```

Probably you need to change this line to something like:
```
RUN CGO_ENABLED=1 go build -o /dnsperfcgo
```

**Comment by uroy-personal** [comment]
> I've tried to build image with your change and looks like `make build` fails with error:
> 
> ```
> Step 5/12 : RUN CGO_ENABLED=1 go build -o dnsperfcgo main.go
>  ---> Running in c113e8d69e75
> go: downloading golang.org/x/net v0.0.0-20200625001655-4c5254603344
> # command-line-arguments
> ./main.go:72:25: undefined: startMetricsServer
> ./main.go:73:2: undefined: registerMetrics
> ./main.go:144:3: undefined: dnsErrorsCounter
> ./main.go:148:3: undefined: dnsTimeoutsCounter
> ./main.go:151:2: undefined: dnsLookupsCounter
> ./main.go:163:3: undefined: dnsLatency
> ```
> 
> Probably you need to change this line to something like:
> 
> ```
> RUN CGO_ENABLED=1 go build -o /dnsperfcgo
> ```

Hi @marseel ,
Thanks for the suggestion. I have updated the Dockerfile accordingly and build succeeded in my MAC. Could you please take the latest changes and try building again.  If it works then I will squash and merge the pull request with a single clear message.

Best Regards,
Umesh

**Comment by marseel** [comment]
Works for me, please squash commits and thanks for contribution.
/ok-to-test

**Comment by uroy-personal** [comment]
> Works for me, please squash commits and thanks for contribution.

Done. Please check and let me know if any issues. Thanks a lot @marseel..

**Pull request merged**
