### PR TITLE
Use jq to format Grafana dashboards in json files

### PR DESCRIPTION
**Pull request by oxddr**
Also add make target to simplify usage for other contributors.

/kind cleanup
/assign @mm4tt

### CODE REVIEW

**Comment by mborsz** [comment]
Nice, thanks
/ok-to-test
/lgtm
/approve

**Comment by mm4tt** [comment]
Nice, can we have it in the verify/ dir (and in the verify + print command how to fix form) and run it as a part of presubmit?

**Comment by oxddr** [comment]
> Nice, can we have it in the verify/ dir (and in the verify + print command how to fix form) and run it as a part of presubmit?

Done. I am not sure whether travis config is 100% correct.

**Comment by mm4tt** [comment]
Nice, thanks!
/lgtm
/approve

**Comment by mm4tt** [comment]
Oh, looks like there are merge conflicts, please fix

**Comment by oxddr** [comment]
@mm4tt PTAL

**Pull request merged**
