### PR TITLE
Fix perf-tests

### PR DESCRIPTION
**Pull request by wojtek-t**
@sjug FYI: I'm fixing it for the second time.

### CODE REVIEW

**Comment by sjug** [comment]
@wojtek-t I'm sorry did I revert this? I didn't see it in the delta?

**Comment by wojtek-t** [comment]
It is in the diff.

**Comment by sjug** [comment]
@wojtek-t I see, sorry I missed that, and thank you for spotting & fixing. Won't happen again.

**Comment by wojtek-t** [comment]
Fixed compile error.

**Pull request merged**
