### PR TITLE
Experimental Prometheus remote write to Cortex.

### PR DESCRIPTION
**Pull request by mm4tt**
Inspired by the Cortex talks on KubeCon, I allowed myself to setup an experimental [Cortex](https://github.com/cortexproject/cortex) cluster.
The cluster is hosted in my dev project, the grafana for it is available at http://35.237.38.211:3000.

The advantages of using Cortex in addition to Prometheus are:
  * It supports multi-tenancy (we can have a separate tenant per test)
  * Horizontally scalable / highly available - it should be easily able to support the load from our tests (if what authors of Cortex are promising is true)
  * Faster / better query enging - we wouldn't run into prometheus "too many samples" limitations anymore
  * Long term storage - we should be able to store metrics from all our place in single place
  * We'll able to have live dashboards for currently running tests
  * And many more :)

I'd like to experiment with it in our scalability tests.
If anything goes wrong it shouldn't break anything, given how the remote write is implemented in prometheus.

Ref. https://github.com/kubernetes/perf-tests/issues/523

### CODE REVIEW

**Comment by mm4tt** [comment]
/hold
until https://github.com/kubernetes/perf-tests/pull/535 gets merged

**Comment by mm4tt** [comment]
/assign @wojtek-t 

@wojtek-t, could you take a look? I can give a short demo to the team on Monday.

**Comment by wojtek-t** [comment]
I would like to first understand what exactly this is doing - let's make a demo and we will see how to proceed with this.

**Comment by wojtek-t** [comment]
To follow up - @mm4tt showed us how it works. It looks great but there are couple issues to be solve to productionize it. @mm4tt is going to work in his free cycles on productioninzing it a bit more before we proceed with this PR.

**Pull request closed without merging**
