### PR TITLE
Add dashboard showing num of request to GCP.

### PR DESCRIPTION
**Pull request by oxddr**
zMrsMnfP3xo

### CODE REVIEW

**Comment by wojtek-t** [comment]
That is pretty cool !!! [didn't look into the code, but the screenshot is great!]
Thanks @oxddr !

/assign @mborsz

**Comment by oxddr** [comment]
Thanks, Wojtek :)

I've updated the dashboard to make it even more configurable (custom groupby etc.) I've also remove unneeded lines from json. 
Wdv4b8A5HWq

**Comment by mborsz** [comment]
Looks really good thanks!

Does it require setting up custom datasource?
How to do that? Could you include some howto (e.g. screenshot with configuration)?

**Comment by oxddr** [comment]
Yes, it requires a Stackdriver datasource in Grafana. The dashboard has a dropdown, from which you can pick one, if there is more than one defined. 

The script we use to setup Grafana has been updated to provide Stackdriver datasource.

**Comment by oxddr** [comment]
@mborsz friendly ping for the review

**Pull request merged**
