### PR TITLE
Bump kubernetes dependency in jsonify

### PR DESCRIPTION
**Pull request by wojtek-t**
Ref https://github.com/kubernetes/perf-tests/pull/2973

/cc @mboersma

### CODE REVIEW

**Comment by wojtek-t** [comment]
/assign @marseel @tosi3k 

@marseel @tosi3k - if any of you could lgtm?

**Comment by wojtek-t** [comment]
/assign @jprzychodzen 

@jprzychodzen - can you please help with tagging?

**Review by mboersma — APPROVED** [review]
lgtm, but I assume we want a project maintainer to provide the final review.

**Comment by wojtek-t** [comment]
@tosi3k @mboersma - I still need "lgtm" tag :)

**Comment by tosi3k** [comment]
Whoops, sorry...

/lgtm

**Pull request merged**
