### PR TITLE
Switch to endpointslices for the DNS perf test

### PR DESCRIPTION
**Pull request by dpasiukevich**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

Switch from the endpoints to the endpointslices to support more than 1000 endpoints for the perftests.

### CODE REVIEW

**Comment by aojea** [comment]
eastern egg, these jobs need to be updated since are using very old golang images

https://github.com/kubernetes/test-infra/blob/d33244c62fe7a6a6d9f3498561eea5bbd513ac43/config/jobs/kubernetes/sig-scalability/sig-scalability-presubmit-jobs.yaml#L820

https://github.com/kubernetes/test-infra/blob/d33244c62fe7a6a6d9f3498561eea5bbd513ac43/config/jobs/kubernetes/sig-scalability/sig-scalability-presubmit-jobs.yaml#L868

/cc @wojtek-t @mborsz

**Comment by aojea** [comment]
@dpasiukevich https://github.com/kubernetes/test-infra/pull/29508 

> Let's merge on Monday - this can potentially break presubmits on perf-tests repo.
> @mborsz @marseel @shyamjvs - FYI

**Comment by dpasiukevich** [comment]
> @dpasiukevich [kubernetes/test-infra#29508](https://github.com/kubernetes/test-infra/pull/29508)
> 
> > Let's merge on Monday - this can potentially break presubmits on perf-tests repo.
> > @mborsz @marseel @shyamjvs - FYI

Cool, thanks! Let's hope that PR would potentially fix presubmits on perf-tests repo. 🗿

**Comment by dpasiukevich** [comment]
Ok, rebased onto latest master and also updated the prometheus lib. Let's see the linter run. If it fails then it's clearly something wrong with the PR changes.

**Comment by dpasiukevich** [comment]
Closing in favor of https://github.com/kubernetes/perf-tests/pull/2284

**Pull request closed without merging**
