### PR TITLE
Better perf-tests reporting - backport to release-1.19

### PR DESCRIPTION
**Pull request by tosi3k**
Backports #1472, #1436, #1478 and #1486 to have nicer performance tests reporting in Prow.

/assign @jkaniuk @wojtek-t

### CODE REVIEW

**Comment by tosi3k** [comment]
> @tosi3k: The following test **failed**, say `/retest` to rerun all failed tests:
> 
> Test name	Commit	Details	Rerun command
> pull-perf-tests-verify-lint	[7cd80c9](https://github.com/kubernetes/perf-tests/commit/7cd80c9ca1c243f60af7d487b3c15e9db5041f39)	[link](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/perf-tests/1492/pull-perf-tests-verify-lint/1309502674483286016)	`/test pull-perf-tests-verify-lint`
> [Full PR test history](https://prow.k8s.io/pr-history?org=kubernetes&repo=perf-tests&pr=1492). [Your PR dashboard](https://prow.k8s.io/pr?query=is%3Apr%20state%3Aopen%20author%3Atosi3k). Please help us cut down on flakes by [linking to](https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests) an [open issue](https://github.com/kubernetes/perf-tests/issues?q=is:issue+is:open) when you hit one in your PR.

Fixing this would require backporting #1482... :D

**Comment by wojtek-t** [comment]
@tosi3k - it seems we need to first backport the changes that fixed bitbucket dependency you did recently

**Comment by tosi3k** [comment]
@wojtek-t yup, I noticed that already. Here's the backport of that fix: #1496.

**Pull request merged**
