### PR TITLE
Delete Redundant "extended load test" override files

### PR DESCRIPTION
**Pull request by maniSbindra**
This PR deletes the redundant [override files](https://github.com/kubernetes/perf-tests/tree/master/clusterloader2/testing/load/experimental/overrides) , and fixes the issue #1036 .

After PR https://github.com/kubernetes/test-infra/pull/17034 is merged, the [override files](https://github.com/kubernetes/perf-tests/tree/master/clusterloader2/testing/load/experimental/overrides) are redundant and can be deleted.

### CODE REVIEW

**Comment by wojtek-t** [comment]
@maniSbindra - thanks for this PR; it seems fine from OSS perspective, but we also need to update our internal tests in Google to stop referencing those files. once they are fixed, i will approve this PR.

/assign

**Comment by maniSbindra** [comment]
Thanks @wojtek-t

**Pull request merged**
