### PR TITLE
Run dnsclient as a deployment in DNS performance tests

### PR DESCRIPTION
**Pull request by prameshj**
This change supports running dnsclient as a deployment. The replicas can be configured by editing the cluster/dnsperf-deploy.py, it will be made configurable in a followup change. This will help measure ClusterDNS and NodeLocal DNSCache performance at scale.

### CODE REVIEW

**Comment by prameshj** [comment]
cc @mm4tt @bowei

**Comment by mm4tt** [comment]
Forgive my ignorance,  I know nothing about the DNS performance test, but it sounds interesting.
Is the test run continuously somewhere? If so, could you link to a test grid? What exactly the test does?

Thanks!

/lgtm
/hold

Feel free to void whenever you want (e.g. if you want to get @bowei's approval)

**Comment by prameshj** [comment]
> Forgive my ignorance, I know nothing about the DNS performance test, but it sounds interesting.
> Is the test run continuously somewhere? If so, could you link to a test grid? What exactly the test does?
> 
> Thanks!
> 
> /lgtm
> /hold
> 
> Feel free to void whenever you want (e.g. if you want to get Bowei Du's approval)

Thanks Matt! The test is run continuously here:
http://perf-dash.k8s.io/#/?jobname=kube-dns%20benchmark
http://perf-dash.k8s.io/#/?jobname=node-local-dns%20benchmark 

I have added more description in https://github.com/kubernetes/perf-tests/blob/master/dns/README.md

The test brings up one dnsclient pod on a GCE k8s cluster and sends DNS requests using dnsperf. We gather latency and QPS metrics. This PR allows us to run a deployment rather than a single pod so we can run this test on larger clusters and generate more DNS load.

**Comment by mm4tt** [comment]
Nice, thanks for explaining!

**Pull request merged**
