### PR TITLE
Generate godep for network

### PR DESCRIPTION
**Pull request by gmarek**
This should help with travis.

cc @jeremyeder

### CODE REVIEW

**Comment by bowei** [comment]
@gmarek Could you separate the vendored files in a different commit? It's quite hard to read in the github review UI.

**Comment by gmarek** [comment]
This PR consists only (nearly) of vendored files - they were missing in networking test.

**Comment by jeremyeder** [comment]
Question:  Is there a SIG that sponsors this test?

**Comment by gmarek** [comment]
It was submitted by @thockin

**Comment by gmarek** [comment]
I just took a look at number of lines added and it made me sad... It's mostly k8s go-client and it's dependencies.

**Comment by bowei** [comment]
LGTM

**Pull request merged**
