### PR TITLE
Fix cpu requests in load test when density test is enabled.

### PR DESCRIPTION
**Pull request by marseel**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Fixes cpu requests in load test when density test is enabled.
Example failed test: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/1310988110418415616
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by wojtek-t** [comment]
Something doesn't work with retesting - @jprzychodzen 

I'm going to merge manually to fix the 5k test regression.

**Comment by jprzychodzen** [comment]
Thanks, I was already checking logs of Prow to see if we need to act on this. It's possible that with all recent changes some strange state happened. There was an unexpected abort for this job after ~30 minutes of runtime. I will validate that presubmits work as expected.

**Pull request merged**
