### PR TITLE
[Travis] Add support to skip some go build targets

### PR DESCRIPTION
**Pull request by jprzychodzen**
A follow up to #993

### CODE REVIEW

**Comment by mm4tt** [comment]
Looks like the build.sh failed, please fix

**Comment by jprzychodzen** [comment]
Travis uses 'GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)' version - it throws an error (unbound variable) while accessing 0 length array.

Removed `set -u` sanity check.

**Comment by mm4tt** [comment]
/lgtm
/approve

Thanks!

**Pull request merged**
