### PR TITLE
Independence from 'verify/verify-flags/known-flags.txt'

### LINKED ISSUE #997: Get rid of verify/verify-flags/known-flags.txt
It's burdensome to update this file every time we add a new flag, we should modify the `verify/verify-flags-underscore.py` to stop reading it and get rid of the `known-flags.txt` file

### PR DESCRIPTION
**Pull request by ChakshuGupta13**
Remove dependence from 'verify/verify-flags/known-flags.txt' of 'verify/verify-flags-underscore.py'. The 'verify/verify-flags-underscore.py' script will have to just go over all *.go files in the repo (except certain directories and files) and check that all flags are in the proper format.

Fix #997

### CODE REVIEW

**Comment by mm4tt** [comment]
Thanks for sending! Please sign the CLA, it's required to merge the PR - https://identity.linuxfoundation.org/projects/cncf

**Comment by ChakshuGupta13** [comment]
I have signed it.

**Comment by mm4tt** [comment]
The travis presubmit should get fixed once https://github.com/kubernetes/perf-tests/pull/1009 merges

**Comment by mm4tt** [comment]
You can re-trigger the travis presubmit by closing and re-opening the PR

**Comment by ChakshuGupta13** [comment]
> You can re-trigger the travis presubmit by closing and re-opening the PR

Thanks @mm4tt 
The build is now passing!

**Comment by mm4tt** [comment]
Nice, thanks!

/lgtm
/approve

**Pull request merged**
