### PR TITLE
ref to [Fix TLS Config in load test clients](https://github.com/kuber…

### PR DESCRIPTION
**Pull request by chaochn47**
…netes/kubernetes/pull/73500)

This PR will allow to run against EKS clusters. Similar to https://github.com/kubernetes/kubernetes/pull/73500

Otherwise, 
```
git checkout master
cd clusterloader2
go run cmd/clusterloader.go --kubeconfig=<kubeconfigfilePath> --testconfig=<configfilePath>
go: downloading k8s.io/kubernetes v1.18.0
go: downloading k8s.io/api v0.18.0
go: downloading github.com/onsi/ginkgo v1.11.0
go: downloading golang.org/x/sync v0.0.0-20190911185100-cd5d95a43a6e
go: downloading k8s.io/apiserver v0.18.0
go: downloading github.com/onsi/gomega v1.7.0
go: downloading k8s.io/cri-api v0.18.0
go: downloading k8s.io/kubectl v0.18.0
go: downloading github.com/pkg/errors v0.8.1
go: downloading k8s.io/cloud-provider v0.18.0
go: downloading google.golang.org/grpc v1.26.0
go: downloading sigs.k8s.io/apiserver-network-proxy/konnectivity-client v0.0.7
go: downloading google.golang.org/genproto v0.0.0-20190819201941-24fa4b261c55
F0518 15:10:22.970051   62061 clusterloader.go:230] Client creation error: creating clientset failed: using a custom transport with TLS certificate options or the insecure flag is not allowed
exit status 1
```
/cc shyamjvs

### CODE REVIEW

**Comment by shyamjvs** [comment]
/ok-to-test
/approve
/lgtm

Will let @wojtek-t or @mm4tt to also give sign-off. For context - we're trying to test cluster-loader with EKS and see if it works.

**Comment by shyamjvs** [comment]
Oops.. it seems like it got auto-merged as soon as I lgtm'd. I was under the impression we were still manually hitting merge for this repo. Sorry.

Matt/Wojtek - If you have comments please drop them here anyway.

**Comment by wojtek-t** [comment]
LGTM

**Pull request merged**
