### PR TITLE
Module for service creation/deletion

### PR DESCRIPTION
**Pull request by mm4tt**

### CODE REVIEW

**Comment by mm4tt** [comment]
Let's wait for presubmits in https://github.com/kubernetes/perf-tests/pull/1641 and https://github.com/kubernetes/perf-tests/pull/1639 to finish. They will generate a yaml files with dumped executable steps. We expect them to be identical which will prove that these change is no-op

**Comment by mm4tt** [comment]
The files are identical:
- https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/perf-tests/1641/pull-perf-tests-clusterloader2/1339212859346784256/artifacts/steps.yaml
- https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/perf-tests/1639/pull-perf-tests-clusterloader2/1339200901872619520/artifacts/steps.yaml


This is safe to merge

/assign @mborsz 
/assing @jkaniuk

**Comment by wojtek-t** [comment]
/lgtm

/hold
Let's not merge on right pretty much everyone will be out for the next 2 weeks or so.

**Comment by mm4tt** [comment]
I wrote a tool to ease the migration. It expands modules to executable steps and compare them against master. The tool is here - https://github.com/mm4tt/k8s-util/tree/master/experimental/cl2-compare-config

```
[hi on] mmatejczyk@mmat ~ $ go get -d -u github.com/mm4tt/k8s-util/experimental/cl2-compare-config
[hi on] mmatejczyk@mmat ~ $ $GOPATH/src/github.com/mm4tt/k8s-util/experimental/cl2-compare-config/run.sh 1640
Cloning perf-test master and 1640 PR
Cloning into 'perf-tests'...
remote: Enumerating objects: 43, done.
remote: Counting objects: 100% (43/43), done.
remote: Compressing objects: 100% (35/35), done.
remote: Total 53846 (delta 18), reused 24 (delta 8), pack-reused 53803
Receiving objects: 100% (53846/53846), 70.29 MiB | 7.31 MiB/s, done.
Resolving deltas: 100% (26738/26738), done.
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Total 8 (delta 6), reused 6 (delta 6), pack-reused 2
Unpacking objects: 100% (8/8), 1005 bytes | 335.00 KiB/s, done.
From https://github.com/kubernetes/perf-tests
 * [new ref]           refs/pull/1640/head -> pr1640
Cloning mm4tt's cl2 copy for dumping test config
Cloning into 'perf-tests'...
remote: Enumerating objects: 51798, done.
remote: Total 51798 (delta 0), reused 0 (delta 0), pack-reused 51798
Receiving objects: 100% (51798/51798), 69.94 MiB | 18.12 MiB/s, done.
Resolving deltas: 100% (25190/25190), done.
Dumping config steps for master
Already on 'master'
Your branch is up to date with 'origin/master'.
I0118 09:36:42.670158 3473628 clusterloader.go:260] Using config: {ClusterConfig:{KubeConfigPath:/dev/null RunFromCluster:false Nodes:100 Provider:0xc0003d0280 EtcdCertificatePath:/etc/srv/kubernetes/pki/etcd-apiserver-server.crt EtcdKeyPath:/etc/srv/kubernetes/pki/etcd-apiserver-server.key EtcdInsecurePort:2382 MasterIPs:[] MasterInternalIPs:[] MasterName: DeleteStaleNamespaces:false DeleteAutomanagedNamespaces:true APIServerPprofByClientEnabled:true KubeletPort:10250} ReportDir:/tmp/cl2-compare-zdGtw0LrG8 EnableExecService:false TestScenario:{Identifier: ConfigPath: OverridePaths:[]} ModifierConfig:{OverwriteTestConfig:[] SkipSteps:[]} PrometheusConfig:{EnableServer:false TearDownServer:false ScrapeEtcd:true ScrapeNodeExporter:false ScrapeKubelets:false ScrapeKubeProxy:true ScrapeNodeLocalDNS:false SnapshotProject:mmatejczyk-gke-dev ManifestPath:$GOPATH/src/k8s.io/perf-tests/clusterloader2/pkg/prometheus/manifests CoreManifests: DefaultServiceMonitors: MasterIPServiceMonitors: NodeExporterPod:}}
W0118 09:36:42.670411 3473628 imagepreload.go:86] No images specified. Skipping image preloading
I0118 09:36:42.670437 3473628 clusterloader.go:213] --------------------------------------------------------------------------------
I0118 09:36:42.670447 3473628 clusterloader.go:214] Running testing/load/config.yaml
I0118 09:36:42.670452 3473628 clusterloader.go:215] --------------------------------------------------------------------------------
I0118 09:36:42.682743 3473628 modules.go:90] Test config successfully dumped to: /tmp/cl2-compare-zdGtw0LrG8/steps.yaml
I0118 09:36:42.682781 3473628 test.go:103] Step dump complete. Exiting...
Dumping config steps for PR 1640
Switched to branch 'pr1640'
I0118 09:36:46.021055 3473873 clusterloader.go:260] Using config: {ClusterConfig:{KubeConfigPath:/dev/null RunFromCluster:false Nodes:100 Provider:0xc000491180 EtcdCertificatePath:/etc/srv/kubernetes/pki/etcd-apiserver-server.crt EtcdKeyPath:/etc/srv/kubernetes/pki/etcd-apiserver-server.key EtcdInsecurePort:2382 MasterIPs:[] MasterInternalIPs:[] MasterName: DeleteStaleNamespaces:false DeleteAutomanagedNamespaces:true APIServerPprofByClientEnabled:true KubeletPort:10250} ReportDir:/tmp/cl2-compare-zdGtw0LrG8 EnableExecService:false TestScenario:{Identifier: ConfigPath: OverridePaths:[]} ModifierConfig:{OverwriteTestConfig:[] SkipSteps:[]} PrometheusConfig:{EnableServer:false TearDownServer:false ScrapeEtcd:true ScrapeNodeExporter:false ScrapeKubelets:false ScrapeKubeProxy:true ScrapeNodeLocalDNS:false SnapshotProject:mmatejczyk-gke-dev ManifestPath:$GOPATH/src/k8s.io/perf-tests/clusterloader2/pkg/prometheus/manifests CoreManifests: DefaultServiceMonitors: MasterIPServiceMonitors: NodeExporterPod:}}
W0118 09:36:46.021205 3473873 imagepreload.go:86] No images specified. Skipping image preloading
I0118 09:36:46.021222 3473873 clusterloader.go:213] --------------------------------------------------------------------------------
I0118 09:36:46.021247 3473873 clusterloader.go:214] Running testing/load/config.yaml
I0118 09:36:46.021258 3473873 clusterloader.go:215] --------------------------------------------------------------------------------
I0118 09:36:46.034447 3473873 modules.go:90] Test config successfully dumped to: /tmp/cl2-compare-zdGtw0LrG8/steps.yaml
I0118 09:36:46.034489 3473873 test.go:103] Step dump complete. Exiting...
Master config dumped in /tmp/cl2-compare-zdGtw0LrG8/master-steps.yaml
PR 1640 config dumped in /tmp/cl2-compare-zdGtw0LrG8/pr1640-steps.yaml
Diff stored in /tmp/cl2-compare-zdGtw0LrG8/diff
Diff is:
```

As we can see the diff is empty in case of this PR. It's safe to merge.

**Comment by mm4tt** [comment]
/assign @tosi3k

Assigning to the current scalability oncall

**Comment by tosi3k** [comment]
/lgtm

Thanks!

**Pull request merged**
