### PR TITLE
Improve perfdash container build

### PR DESCRIPTION
**Pull request by skurtzemann**
This PR is to resolve issue #604 as seen with @oxddr

### CODE REVIEW

**Comment by oxddr** [comment]
Looks good, thanks!

Can you please squash commits into a single one? Otherwise LGTM.

**Comment by skurtzemann** [comment]
> Looks good, thanks!
> 
> Can you please squash commits into a single one? Otherwise LGTM.

Ok I will squash commits.

Another question, do I also need to
- bump `TAG` info `Makefile` and by the way update `deployment.yaml` 
- update `container` target into `Makefile` which will no more depend of `perfdash` target

**Comment by oxddr** [comment]
> * bump `TAG` info `Makefile` and by the way update `deployment.yaml`

I'll take care of this at the same time I'll upgrade perfdash, since you don't have an access to GCP project running perf-dash. 

> * update `container` target into `Makefile` which will no more depend of `perfdash` target

Please do, in this PR ideally.

**Comment by skurtzemann** [comment]
> > * bump `TAG` info `Makefile` and by the way update `deployment.yaml`
> 
> I'll take care of this at the same time I'll upgrade perfdash, since you don't have an access to GCP project running perf-dash.
> 
> > * update `container` target into `Makefile` which will no more depend of `perfdash` target
> 
> Please do, in this PR ideally.

PR is updated :)

**Comment by oxddr** [comment]
/ok-to-test
/lgtm
/approve 

Thanks a lot for the PR!

**Pull request merged**
