### PR TITLE
fix "./run  core-dns out" failed

### LINKED ISSUE #864: exec `./run core-dns out ` got `error gettings dns ip for service kube-dns`
Hello, I clone the newest code, and I exec `./run core-dns out` got `error gettings dns ip for service kube-dns`
```shell
root@master1:~/xujingsong/perf-tests/dns# ./run core-dns out
Requirement already satisfied (use --upgrade to upgrade): numpy in /usr/lib/python2.7/dist-packages
INFO 10-22 10:56:04 runner.py:77] Using cluster DNS for tests
Traceback (most recent call last):
  File "py/run_perf.py", line 118, in <module>
    runner = Runner(args)
  File "/root/xujingsong/perf-tests/dns/py/runner.py", line 78, in __init__
    self.args.dns_ip = self._get_dns_ip("kube-dns")
  File "/root/xujingsong/perf-tests/dns/py/runner.py", line 335, in _get_dns_ip
    raise Exception('error gettings dns ip for service %s: %d' %(svcname, code))
Exception: error gettings dns ip for service kube-dns: 1

```

### PR DESCRIPTION
**Pull request by xieyanker**
fix #864

### CODE REVIEW

**Comment by prameshj** [comment]
@xieyanker can you describe what the failure is? Isn't the service called "kube-dns" for a cluster running coreDNS as well?

**Comment by xieyanker** [comment]
@prameshj I found the source code is always "kube-dns"
https://github.com/kubernetes/perf-tests/blob/b14532032f5e6606ff2f76afd7abc30e83b8b23c/dns/py/runner.py#L78
And I repush the code, make it use the `dns_server` from the param

This is my coredns service in k8s:
```shell
root@master1:~# kubectl get svc -nkube-system
NAME                     TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                  AGE
coredns                  ClusterIP   172.30.0.3      <none>        53/UDP,53/TCP,9153/TCP   54d
```

**Comment by xieyanker** [comment]
Before I change the code, I got:
```shell
root@master1:~/xujingsong/perf-tests/dns# ./run core-dns out
Requirement already satisfied (use --upgrade to upgrade): numpy in /usr/lib/python2.7/dist-packages
INFO 10-22 10:56:04 runner.py:77] Using cluster DNS for tests
Traceback (most recent call last):
  File "py/run_perf.py", line 118, in <module>
    runner = Runner(args)
  File "/root/xujingsong/perf-tests/dns/py/runner.py", line 78, in __init__
    self.args.dns_ip = self._get_dns_ip("kube-dns")
  File "/root/xujingsong/perf-tests/dns/py/runner.py", line 335, in _get_dns_ip
    raise Exception('error gettings dns ip for service %s: %d' %(svcname, code))
Exception: error gettings dns ip for service kube-dns: 1
```
After:
```shell
root@master1:~/xujingsong/perf-tests/dns# ./run core-dns out
Requirement already satisfied (use --upgrade to upgrade): numpy in /usr/lib/python2.7/dist-packages
You are using pip version 8.1.1, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
INFO 10-22 14:14:03 runner.py:77] Using cluster DNS for tests
INFO 10-22 14:14:03 runner.py:87] DNS service IP is 172.30.0.3
INFO 10-22 14:14:05 runner.py:316] Client node is master2
INFO 10-22 14:14:05 runner.py:462] Created rundir out/run-1571724845
INFO 10-22 14:14:05 runner.py:468] Updated symlink out/latest
INFO 10-22 14:14:05 runner.py:408] Starting client teardown
INFO 10-22 14:14:06 runner.py:418] Client teardown complete
INFO 10-22 14:14:06 runner.py:174] Create Pod/dns-perf-client ok
INFO 10-22 14:14:06 runner.py:371] Client pod to started on master2
```

**Comment by prameshj** [comment]
Should we also change run.sh to pass in the --dns-server argument correctly?

**Comment by prameshj** [comment]
It would be great if you can verify if "./run core-dns out" works. Optionally, if you can verify "./run kube-dns out" works, that would be great. Just create a custom service called "kube-dns" on your same cluster with the same selectors as the coreDNS service. Make sure the tests run and get some non-zero QPS.

**Comment by xieyanker** [comment]
@prameshj Sorry. I ignore the `kube-dns`, I think it also should be transfered with the `--dns-server` argument. I will repush immediately.

**Comment by xieyanker** [comment]
@prameshj  I have repushed the code, and pass transform the param for `kube-dns`

**Comment by prameshj** [comment]
Change looks good.. could you please verify that it works by running the test?

**Comment by xieyanker** [comment]
It seems no problem for `kbue-dns`
```shell
root@master1:~/xujingsong/perf-tests/dns# ./run core-dns out
Requirement already satisfied (use --upgrade to upgrade): numpy in /usr/lib/python2.7/dist-packages
You are using pip version 8.1.1, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
INFO 10-22 14:14:03 runner.py:77] Using cluster DNS for tests
INFO 10-22 14:14:03 runner.py:87] DNS service IP is 172.30.0.3
INFO 10-22 14:14:05 runner.py:316] Client node is master2
INFO 10-22 14:14:05 runner.py:462] Created rundir out/run-1571724845
INFO 10-22 14:14:05 runner.py:468] Updated symlink out/latest
```
```
root@master1:~/xujingsong/perf-tests/dns# ./run kube-dns out
Requirement already satisfied (use --upgrade to upgrade): numpy in /usr/lib/python2.7/dist-packages
You are using pip version 8.1.1, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
INFO 10-22 14:56:54 runner.py:77] Using cluster DNS for tests
INFO 10-22 14:56:55 runner.py:87] DNS service IP is 172.30.0.4
INFO 10-22 14:56:57 runner.py:316] Client node is master2
INFO 10-22 14:56:57 runner.py:462] Created rundir out/run-1571727417
INFO 10-22 14:56:57 runner.py:468] Updated symlink out/latest
INFO 10-22 14:56:57 runner.py:408] Starting client teardown
INFO 10-22 14:57:02 runner.py:418] Client teardown complete
INFO 10-22 14:57:02 runner.py:174] Create Pod/dns-perf-client ok
INFO 10-22 14:57:03 runner.py:371] Client pod to started on master2
```

```shell
root@master1:~# kubectl get svc -nkube-system |grep dns
coredns                  ClusterIP   172.30.0.3      <none>        53/UDP,53/TCP,9153/TCP   54d
kube-dns                 ClusterIP   172.30.0.4      <none>        53/UDP,53/TCP,9153/TCP   13s
```

**Pull request merged**
