### PR TITLE
Profile measurements should warn instead of fail on lack of master IPs

### PR DESCRIPTION
**Pull request by jkaniuk**
Profile measurements should warn instead of fail on lack of master IPs

Currently it fails tests with:
```
[measurement call TestMetrics - TestMetrics error: [
Profile measurements will be disabled due to no MasterIps 
Profile measurements will be disabled due to no MasterIps 
Profile measurements will be disabled due to no MasterIps 
Profile measurements will be disabled due to no MasterIps 
Profile measurements will be disabled due to no MasterIps 
Profile measurements will be disabled due to no MasterIps 
Profile measurements will be disabled due to no MasterIps 
Profile measurements will be disabled due to no MasterIps 
Profile measurements will be disabled due to no MasterIps
]]
```

/assign @mm4tt

### CODE REVIEW

**Comment by mm4tt** [comment]
/lgtm
/approve

Thanks!

**Comment by jkaniuk** [comment]
Regression introduced by: #891

@alejandrox1 - FYI

**Pull request merged**
