### PR TITLE
Add CloudProvider to the MeasurementConfig.

### PR DESCRIPTION
**Pull request by mm4tt**
It will be needed to disable Probes measurement in kubemark, see https://github.com/kubernetes/perf-tests/pull/475#discussion_r274874178

### CODE REVIEW

**Comment by wojtek-t** [comment]
```
$ ./verify/verify-gofmt.sh
!!! 'gofmt -s' needs to be run on the following files: 
./clusterloader2/pkg/measurement/manager.go
The command "./verify/verify-gofmt.sh" exited with 1
```

Other than that lgtm

**Comment by mm4tt** [comment]
> ```
> $ ./verify/verify-gofmt.sh
> !!! 'gofmt -s' needs to be run on the following files: 
> ./clusterloader2/pkg/measurement/manager.go
> The command "./verify/verify-gofmt.sh" exited with 1
> ```
> Other than that lgtm

Done

**Pull request merged**
