### PR TITLE
Customize enabling of immutable secrets and configmaps in CL2

### PR DESCRIPTION
**Pull request by tosi3k**
/assign @wojtek-t

### CODE REVIEW

**Comment by mm4tt** [comment]
I'm afraid this is not enough. To make it work we'll also need to take into account changes made in the deployment.yaml in the https://github.com/kubernetes/perf-tests/commit/688f020031489a6ecdf2afea92323a8f2d99d80b

**Comment by tosi3k** [comment]
> I'm afraid this is not enough. To make it work we'll also need to take into account changes made in the deployment.yaml in the [688f020](https://github.com/kubernetes/perf-tests/commit/688f020031489a6ecdf2afea92323a8f2d99d80b)

Good point, thanks. Had to perform larger config gymnastics because of that :grinning:.

**Comment by wojtek-t** [comment]
TBH - because of that, I'm not the fan of this change...

**Pull request merged**
