### PR TITLE
Remove vendor directory from slo-monitor

### PR DESCRIPTION
**Pull request by tosi3k**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Follow-up to https://github.com/kubernetes/perf-tests/pull/1482.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
/cc @mm4tt @mborsz 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by mm4tt** [comment]
657k lines removed, nice!  👍 

/lgtm
/approve

**Comment by mm4tt** [comment]
I forgot that the test is not blocking. @tosi3k, could you take a look into the failure? I'd like to make sure this PR doesn't break anything

**Comment by tosi3k** [comment]
> I forgot that the test is not blocking. @tosi3k, could you take a look into the failure? I'd like to make sure this PR doesn't break anything

Looks like an error related to interruption by the PR merge, so nothing to worry about (PTAL at the last line):
```
# TODO(oxddr): allow tests to fail, until we get confidence in the new presubmit
verify/test.sh
Running tests with GO111MODULE=off...
ok  	k8s.io/perf-tests/compare/src	0.598s
?   	k8s.io/perf-tests/compare/src/main	[no test files]
?   	k8s.io/perf-tests/dns/jsonify	[no test files]
Running tests with GO111MODULE=on...
go: downloading github.com/dgryski/go-onlinestats v0.0.0-20170612111826-1c7d19468768
(...)
go: finding github.com/opencontainers/go-digest v1.0.0-rc1
{"component":"entrypoint","file":"prow/entrypoint/run.go:169","func":"k8s.io/test-infra/prow/entrypoint.Options.ExecuteProcess","level":"error","msg":"Entrypoint received interrupt: terminated","severity":"error","time":"2020-09-21T14:58:43Z"}
```
I ran `make verify-all` beforehand locally and it worked as well.

**Pull request merged**
