### PR TITLE
remove automanaged ns

### LINKED ISSUE #1696: Remove deprecated automanagedNamespaces
AutomanagedNamespaces has been deprecated but is still being used in `node-throughput` and `windows-tests` configs. These configs are used in sig-scalability periodic jobs and sig-windows tests.

### PR DESCRIPTION
**Pull request by rahulii**
**What type of PR is this?**
/kind bug
/kind failing-test

**What this PR does / why we need it**:
This PR removes the usage of deprecated automanaged ns, in continuation of #1806 
**Which issue(s) this PR fixes**:

Part of #1696 

**Special notes for your reviewer**:
[WIP]
**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by marseel** [comment]
There is a few more places where AutomanagedNamespaces could be removed, could you also remove them :)?

**Comment by rahulii** [comment]
@marseel  could you check now?

**Comment by marseel** [comment]
/remove-kind failing-test
/remove-kind bug
/kind cleanup

Generally looks good, but I think we missed this test: https://github.com/kubernetes/perf-tests/blob/master/clusterloader2/testing/network/config.yaml#L6
Could you open another PR where we migrate this test to namespaces, please?

**Comment by rahulii** [comment]
> namespaces

Sure!I l'll do that!

**Comment by rahulii** [comment]
> /remove-kind failing-test
> /remove-kind bug
> /kind cleanup
> 
> Generally looks good, but I think we missed this test: https://github.com/kubernetes/perf-tests/blob/master/clusterloader2/testing/network/config.yaml#L6
> Could you open another PR where we migrate this test to namespaces, please?

Sure I'll do that!

**Comment by rahulii** [comment]
@marseel , think we can now merge this one!

**Pull request closed without merging**
