### PR TITLE
Make run-e2e.sh print commit history

### PR DESCRIPTION
**Pull request by mm4tt**

### CODE REVIEW

**Comment by mm4tt** [comment]
/hold

Wait for https://github.com/kubernetes/test-infra/pull/20062

**Comment by mborsz** [comment]
I guess this should happen as part of bootstrap.py where we fetch repos and write infra-commit and other fields in finished.json

**Comment by mm4tt** [comment]
> I guess this should happen as part of bootstrap.py where we fetch repos and write infra-commit and other fields in finished.json

Yeah, I considered that, but bootstrap is deprecated and we'll have a pushback making changes there. We should migrate to pod-utils, but that's a bigger project (e.g. we'll have to rewrite log-exporter). This is a hacky solution to fix the problem for now. I'll add a TODO to get rid of this once we migrate to pod-utils.

**Pull request merged**
