### PR TITLE
Migrate network package to Go modules

### PR DESCRIPTION
**Pull request by oxddr**
ref https://github.com/kubernetes/perf-tests/issues/1099

/assign @mm4tt 
/assign @wojtek-t 

Matt, Wojtek - is this package used anywhere, so I can test whether it has not broken anything? It builds just fine on my machine. I've created this PR to unblock https://github.com/kubernetes/perf-tests/pull/1219.

### CODE REVIEW

**Comment by prameshj** [comment]
Change itself looks ok. But I have not used tests in the network package, so can't comment on whether anything can break as a result of this change. Tagging @alegacy @qckzr who have made changes to the network package recently to comment on this.

**Comment by mm4tt** [comment]
/approve
/hold

Please wait for the lgtm from @alegacy or @qckzr

**Comment by qckzr** [comment]
if tests are passing I'd say lgtm 👍 !

**Pull request merged**
