### PR TITLE
Migrate perfdash to Go modules

### PR DESCRIPTION
**Pull request by oxddr**
It was simple to migrate the perfdash to Go modules, than debugging obsolete godep.

### CODE REVIEW

**Comment by mm4tt** [comment]
/lgtm
/approve

/hold
Before submitting, can we try building new version of perf-dash and deploying it? I want to make sure that it doesn't break anything

**Comment by shyamjvs** [comment]
@oxddr Is this PR still something you want to do? It'll help if we can merge this, so it'll be easy to make changes using go mod going forward.

**Comment by oxddr** [comment]
@shyamjvs I'll try to finish this PR this week.

**Comment by wojtek-t** [comment]
This has happened in the meantime.

**Pull request closed without merging**
