### PR TITLE
Regenerate master dashboard

### PR DESCRIPTION
**Pull request by pytimer**
Regenerate master-dashboard.json after rename etcd_disk_backend_commit_duration_seconds to etcd_disk_backend_commit_duration_seconds_bucket in master dashboard.

### CODE REVIEW

**Comment by pytimer** [comment]
@jkaniuk @wojtek-t I send PR to regenerate `master-dashboard.json` file after https://github.com/kubernetes/perf-tests/pull/1372 merged.
Then i occur an error when `make` dashboard. I found a issue about [attrib() got an unexpected keyword argument 'convert' on import ](https://github.com/weaveworks/grafanalib/issues/186), i found the grafanalib 0.5.5 fix it, so should we upgrade grafanalib 0.5.3 to 0.5.5? If upgrade, i send a commit in this PR or another PR to do it?

```bash
# Setting PYTHONPATH to WD is a workaround for https://github.com/weaveworks/grafanalib/issues/58
PYTHONPATH="$PYTHONPATH:/perf-tests/clusterloader2/pkg/prometheus/manifests/dashboards" generate-dashboard  "master-dashboard.dashboard.py" | python3 -m json.tool > "master-dashboard.json"
Traceback (most recent call last):
  File "/usr/local/bin/generate-dashboard", line 8, in <module>
    sys.exit(generate_dashboard_script())
  File "/usr/local/lib/python3.8/site-packages/grafanalib/_gen.py", line 126, in generate_dashboard_script
    run_script(generate_dashboard)
  File "/usr/local/lib/python3.8/site-packages/grafanalib/_gen.py", line 116, in run_script
    sys.exit(f(sys.argv[1:]))
  File "/usr/local/lib/python3.8/site-packages/grafanalib/_gen.py", line 103, in generate_dashboard
    dashboard = load_dashboard(opts.dashboard)
  File "/usr/local/lib/python3.8/site-packages/grafanalib/_gen.py", line 24, in load_dashboard
    module = imp.load_source("dashboard", path)
  File "/usr/local/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/perf-tests/clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.dashboard.py", line 18, in <module>
    from grafanalib import core as g
  File "/usr/local/lib/python3.8/site-packages/grafanalib/core.py", line 449, in <module>
    class Row(object):
  File "/usr/local/lib/python3.8/site-packages/grafanalib/core.py", line 452, in Row
    panels = attr.ib(default=attr.Factory(list), convert=_balance_panels)
TypeError: attrib() got an unexpected keyword argument 'convert'
```

**Comment by jkaniuk** [comment]
/lgtm

As for grafanalib 0.5.3 it works fine on my PC.
`Requirement already satisfied: grafanalib==0.5.3 in ~/.local/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (0.5.3)`

**Comment by pytimer** [comment]
> As for grafanalib 0.5.3 it works fine on my PC.

The grafanalib depends on the `attrs` library, and the 19.03 version of this library make generate dashboard fail, if reinstall `attrs` to 19.02 or 19.01, there are nothing wrong. Does your `attrs` version less than 19.03, so it works well?

**Comment by jkaniuk** [comment]
> > As for grafanalib 0.5.3 it works fine on my PC.
> 
> The grafanalib depends on the `attrs` library, and the 19.03 version of this library make generate dashboard fail, if reinstall `attrs` to 19.02 or 19.01, there are nothing wrong. Does your `attrs` version less than 19.03, so it works well?

Works for me with 19.3.0:

```
$ make
Requirement already satisfied: grafanalib==0.5.3 in /usr/local/google/home/jkaniuk/.local/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (0.5.3)
Requirement already satisfied: attrs in /usr/lib/python3/dist-packages (from grafanalib==0.5.3->-r requirements.txt (line 1)) (19.3.0)

$ pip3 freeze
grafanalib==0.5.3
attrs==19.3.0
```

**Pull request merged**
