### PR TITLE
Make 'go get' in travis script only download packages

### PR DESCRIPTION
**Pull request by shyamjvs**
Ref https://github.com/kubernetes/perf-tests/pull/40

This should hopefully fix the issue with `github.com/Microsoft/go-winio` dependency for benchmark, compare and clusterloader.

cc @gmarek @wojtek-t @sjug

### CODE REVIEW

**Comment by shyamjvs** [comment]
@gmarek Well at least you should've waited for Travis to finish :)

**Comment by gmarek** [comment]
It'd have failed because of cluster-loader.

**Comment by shyamjvs** [comment]
But we could've checked if it fixed the part it needed to :)

**Comment by sjug** [comment]
You realize it still breaks all the same for go test, right?

```
# k8s.io/perf-tests/benchmark/vendor/github.com/Microsoft/go-winio
benchmark/vendor/github.com/Microsoft/go-winio/file.go:45: undefined: syscall.Overlapped
# k8s.io/perf-tests/benchmark/vendor/github.com/seccomp/libseccomp-golang
benchmark/vendor/github.com/seccomp/libseccomp-golang/seccomp.go:25:22: fatal error: seccomp.h: No such file or directory
compilation terminated.
``

**Comment by shyamjvs** [comment]
Yes that's true. That is why I was suggesting delegating to Makefiles of individual directories. It might not be the best solution (as we'd have to iterate over top level diretories), but I guess works good enough until we flatten godeps across the entire repo. For the size of this repo this might be ok to do (no?)

**Pull request merged**
