### PR TITLE
ClusterLoader - Increasing apiserver cpu limit to 2.5

### PR DESCRIPTION
**Pull request by krzysied**
ref https://github.com/kubernetes/kubernetes/issues/75509

### CODE REVIEW

**Comment by wojtek-t** [comment]
Can we first check with PR author that the increase is expected? If so, I'm fine with bumping, if not, we should understand it.

**Comment by krzysied** [comment]
/hold
There is a PR that should fix the issue - https://github.com/kubernetes/kubernetes/pull/75570

**Comment by krzysied** [comment]
/close
kubernetes/kubernetes#75570 fixed the issue

**Pull request closed without merging**
