### PR TITLE
slo-monitor: sync go modules to vendor

### PR DESCRIPTION
**Pull request by oxddr**
This is a prerequisite to make https://github.com/kubernetes/perf-tests/pull/1232 work: vendor and go.mod were out of sync, causing linter to report issues. 

/assign @wojtek-t

### CODE REVIEW

**Comment by oxddr** [comment]
FWIW `pull-perf-tests-verify-lint` is expected to fail.

**Comment by wojtek-t** [comment]
@oxddr - did you try to build the slo-monitor with those changes?

**Comment by oxddr** [comment]
> janluk - did you try to build the slo-monitor with those changes?

Yes, it was compiled just fine.

**Comment by oxddr** [comment]
Note to myself: we need to fix build.sh script and add it to presubmit.

**Pull request merged**
