### PR TITLE
Bump perf-dash to 2.23

### PR DESCRIPTION
**Pull request by mm4tt**
This is to include https://github.com/kubernetes/perf-tests/pull/1172

### CODE REVIEW

**Comment by mm4tt** [comment]
Kicked off reloading perfdash (it will take some time).

**Comment by ingvagabund** [comment]
@mm4tt the perfdash seems to be down

**Comment by mm4tt** [comment]
I think it's still reloading :/

**Comment by ingvagabund** [comment]
It's back up but it looks like it did not pick the latest changes. I can still see `extention_duration_point` prefixed metrics. The prefix is supposed to be gone.

**Comment by mm4tt** [comment]
I messed it up, reloading again, should be good now

**Comment by ingvagabund** [comment]
All good now, thanks!!!

**Pull request merged**
