### PR TITLE
util-images/watch-list: replace `ENABLE_CLIENT_GO_WATCH_LIST_ALPHA` env var with `KUBE_FEATURE_WatchListClient`

### PR DESCRIPTION
**Pull request by p0lyn0mial**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
The previous environment variable is being replaced in https://github.com/kubernetes/kubernetes/pull/122791

#### Which issue(s) this PR fixes:

Fixes #

### CODE REVIEW

**Comment by p0lyn0mial** [comment]
/hold 

until https://github.com/kubernetes/kubernetes/pull/122791 is merged

**Comment by deads2k** [comment]
with https://github.com/kubernetes/kubernetes/pull/122791, this makes sense to me.

/lgtm

keep the hold until both PRs are ready to merge and then you can coordinate merging them.

**Comment by p0lyn0mial** [comment]
@marseel since Wojtek is out would you mind approving his PR?

**Comment by p0lyn0mial** [comment]
the `watch-list` perf tests are[ executed once a day ](https://testgrid.k8s.io/sig-scalability-experiments#watchlist-on)around 10 AM CET. The nearest run is tomorrow morning. There is plenty of time to merge both PRs.

/hold cancel

**Pull request merged**
