### PR TITLE
Upgrade client-go to the latest version in network project

### PR DESCRIPTION
**Pull request by orsoly**
Upgrade from v2.0.0 to v9.0.0.

I'm a first time contributor, happy to receive feedback. Thanks.

### CODE REVIEW

**Comment by wojtek-t** [comment]
@orsoly - thanks for your PR.
Please rebase your PR (the last commit is no longer needed after https://github.com/kubernetes/perf-tests/pull/260).

Also - can you double check if gofmt issues are still there?

**Comment by orsoly** [comment]
@wojtek-t 
The network project (with my changes) can be built with go 1.11, but there are two errors.

The first is a gofmt problem in clusterloader2, I already created an issue ([#254](https://github.com/kubernetes/perf-tests/issues/254)). I can easily fix this one.

The other problem is in perfdash vendor. I'm not sure what the solution is, maybe the godeps should be updated (or just github.com/ghodss/yaml/)? Can help me with this? Thanks in advance.

**Comment by wojtek-t** [comment]
@orsoly - please remove the "Merge remote-tracking branch 'upstream/master'" commit - it's empty.

**Comment by orsoly** [comment]
@wojtek-t - Now i only have the issue in perfdash vendor. Should I create an issue or try to fix it myself?

**Comment by wojtek-t** [comment]
> @wojtek-t - Now i only have the issue in perfdash vendor. Should I create an issue or try to fix it myself?

You can't fix vendor - it's a piece of code that we don't change.
vendor should be excluded from checking  anything codestyle-related. If you have time to do that, it would be great.

**Comment by wojtek-t** [comment]
You can't fix vendor - it's a piece of code that we don't change.
vendor should be excluded from checking anything codestyle-related. If you have time to do that, it would be great.

**Comment by wojtek-t** [comment]
You can't fix vendor - it's a piece of code that we don't change.
vendor should be excluded from checking anything codestyle-related. If you have time to do that, it would be great.

**Comment by orsoly** [comment]
@wojtek-t - Hi, my PR is stuck in the cla/linuxfoundation check state since yesterday. Can you suggest a solution for this?

**Comment by wojtek-t** [comment]
There was github outage. Let me close adn reopen.

**Pull request merged**
