### PR TITLE
Update to go 1.19

### PR DESCRIPTION
**Pull request by ruiwen-zhao**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
Update to go 1.19 

#### Which issue(s) this PR fixes:

Fixes #

### CODE REVIEW

**Comment by jprzychodzen** [comment]
Please bump tag in Makefile.

Is it possible to bump directly to `go1.19.6`?

**Comment by ruiwen-zhao** [comment]
> Please bump tag in Makefile.
> 
> Is it possible to bump directly to `go1.19.6`?

Updated the tag.

I am following https://go.dev/ref/mod#go-mod-file-go, and it looks like we only use minor version in the mod file.

**Comment by ruiwen-zhao** [comment]
@jprzychodzen @wojtek-t gentle ping on the review

**Comment by jprzychodzen** [comment]
> > Please bump tag in Makefile.
> > Is it possible to bump directly to `go1.19.6`?
> 
> Updated the tag.
> 
> I am following https://go.dev/ref/mod#go-mod-file-go, and it looks like we only use minor version in the mod file.

Right, I've mixed it up with a Bazel.

/lgtm
/approve

/assign @marseel 

@marseel , could you approve?

**Pull request merged**
