### PR TITLE
Reverting to the state at 4c0b3a on release1.16 branch

### PR DESCRIPTION
**Pull request by oxddr**
v1.16.0 tag was added on 13-09-2019, 4c0b3a was merged on 12-09-2019.

ref #797

### CODE REVIEW

**Comment by oxddr** [comment]
This has been tested against k/k release-1.16 and worked fine.

**Comment by wojtek-t** [comment]
Tests are failing.

**Comment by oxddr** [comment]
> Tests are failing.

They shouldn't be triggered at all (please see other PRs where I try to update other branches). There were some problems with this PR (see comment about CLA for instance).

**Comment by mm4tt** [comment]
Could you fix somehow the failing tests? 
We won't be able to merge if the tests are failing, right?

**Comment by oxddr** [comment]
I don't think so - they are not being triggered now at all. I am going to create a new PR. 

/close

**Pull request closed without merging**
