### PR TITLE
[ClusterLoader2] Enable measuring API availability for public and/or private IPs

### PR DESCRIPTION
**Pull request by jprzychodzen**
Enable API Availability measurement for public IPs, also add a flag to enable/disable private/public IPs

#### What type of PR is this?

/kind feature

### CODE REVIEW

**Comment by mborsz** [comment]
/hold

Is the change backward compatible? i.e. if someone was using the api availability on internal IPs what will happen?

Can we adjust defaults to match the previous behavior (i.e. true for internal, false for public)?

**Comment by jprzychodzen** [comment]
> Is the change backward compatible?

No, it's not in a current shape. Let's go with internal IPs default to true if `config.ClusterLoaderConfig.ExecServiceConfig.Enable` and `len(config.ClusterFramework.GetClusterConfig().MasterInternalIPs) != 0`. With public IPs default to `false` it will be completly backward compatible.

**Comment by jprzychodzen** [comment]
kubemark test is falling with
```
 - Setting minimum CPU platform is not supported for the selected machine type e2-standard-8.
Failed to create master instance due to non-retryable error
2024/01/30 13:18:34 process.go:155: Step 'test/kubemark/start-kubemark.sh' finished in 1m20.74023594s
```

**Comment by mborsz** [comment]
> kubemark test is falling with
> 
> ```
>  - Setting minimum CPU platform is not supported for the selected machine type e2-standard-8.
> Failed to create master instance due to non-retryable error
> 2024/01/30 13:18:34 process.go:155: Step 'test/kubemark/start-kubemark.sh' finished in 1m20.74023594s
> ```

 I will take care of it

**Pull request merged**
