### PR TITLE
Grammar fixes for the CL2 README.md

### PR DESCRIPTION
**Pull request by mboersma**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

Cleans up some grammar and inconsistencies in `clusterloader2/README.md` to make it easier for new contributors to understand.

#### Which issue(s) this PR fixes:

Fixes #

### CODE REVIEW

**Comment by mboersma** [comment]
@mborsz @wojtek-t please take a look at this cleanup PR.

**Comment by mboersma** [comment]
@marseel could you take a look at this please? There are some significant errors this fixes which will make the project more approachable for new users. Thanks!

**Comment by mborsz** [comment]
/lgtm
/approve

Thanks!

**Pull request merged**
