### PR TITLE
base logger config and template

### PR DESCRIPTION
**Pull request by rflorenc**
Clusterloader logger template

### CODE REVIEW

**Comment by rflorenc** [comment]
@timstclair @sjug @jeremyeder 
This template was already tested with the "old" cluster-loader.py and should be used in the same manner (probably with small modifications) by the new version once it supports OCP.

**Comment by timothysc** [comment]
@rflorenc could you add a readme on usage + example output.

**Comment by rflorenc** [comment]
@timstclair yes, I'll get it done after devconf.

**Comment by rflorenc** [comment]
@timstclair 
`
16:22 $ kubectl cluster-info
Kubernetes master is running at https://192.168.99.100:8443
KubeDNS is running at https://192.168.99.100:8443/api/v1/proxy/namespaces/kube-system/services/kube-dns
kubernetes-dashboard is running at https://192.168.99.100:8443/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard
`

Run with:
`
./e2e.test --host="https://192.168.99.100:8443" --ginkgo.v=true --ginkgo.focus="Cluster Loader" --kubeconfig=/home/rlourenc/.kube/config --viper-config=config/logger
`

[e2e_output.txt](https://github.com/kubernetes/perf-tests/files/755013/e2e_output.txt)
[e2e_output_2.txt](https://github.com/kubernetes/perf-tests/files/755018/e2e_output_2.txt)

**Comment by timothysc** [comment]
@rflorenc I meant update your PR to include a README.md

**Pull request merged**
