### PR TITLE
Backport slow count fix to 1.19

### PR DESCRIPTION
**Pull request by marseel**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Cherry-pick: #1600
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by wojtek-t** [comment]
/hold

Let's have it merged in master first and ensure nothing break.

**Comment by jkaniuk** [comment]
100 and 5k node tests are green on master

/unhold

**Pull request merged**
