### PR TITLE
[1.18] Add custom thresholds mechanism in APIResponsivenessPrometheus measurement

### PR DESCRIPTION
**Pull request by jkaniuk**
Cherry-pick #1276 to 1.18

Needed to cherry-pick other improvements of this measurement.

/cc @wojtek-t
/cc @tosi3k

### CODE REVIEW

**Comment by tosi3k** [comment]
@jkaniuk I think you need to change `measurement.Config` occurrences in the code to `measurement.MeasurementConfig` as the name of the interface was changed in release-1.19.

**Comment by jkaniuk** [comment]
> @jkaniuk I think you need to change `measurement.Config` occurrences in the code to `measurement.MeasurementConfig` as the name of the interface was changed in release-1.19.

Right, done

**Pull request merged**
