### PR TITLE
Use python3 instead of jq to format dashboards.

### PR DESCRIPTION
**Pull request by oxddr**
This removes an external dependecy from presubmit (python3 should be included in
golang docker images).

ref https://github.com/kubernetes/perf-tests/issues/552

/assign @mm4tt

### CODE REVIEW

**Comment by mm4tt** [comment]
I see the following errors in the pull-perf-tests-verify-all 

```
verify/verify-dashboard-format.sh: line 27: python3: command not found
verify/verify-dashboard-format.sh: line 27: python3: command not found
verify/verify-dashboard-format.sh: line 27: python3: command not found
verify/verify-dashboard-format.sh: line 27: python3: command not found
verify/verify-dashboard-format.sh: line 27: python3: command not found
!!! ./verify/verify-dashboard-format.sh --fix need to be run to format dashboards. 
Following dashboards are not formatted correctly: clusterloader2/pkg/prometheus/manifests/dashboards/dns.json
```

Looks like python3 is not found, why the presubmit passed?

**Comment by oxddr** [comment]
> I see the following errors in the pull-perf-tests-verify-all
> 
> ```
> verify/verify-dashboard-format.sh: line 27: python3: command not found
> verify/verify-dashboard-format.sh: line 27: python3: command not found
> verify/verify-dashboard-format.sh: line 27: python3: command not found
> verify/verify-dashboard-format.sh: line 27: python3: command not found
> verify/verify-dashboard-format.sh: line 27: python3: command not found
> !!! ./verify/verify-dashboard-format.sh --fix need to be run to format dashboards. 
> Following dashboards are not formatted correctly: clusterloader2/pkg/prometheus/manifests/dashboards/dns.json
> ```
> 
> Looks like python3 is not found, why the presubmit passed?

1. It seems that it's python2 but not python3 available in golang image. I am going to move this check to a separate presubmit (run only if dashboard are changed)
2. I've fixed the verify script so it exit with 1 code (it was 0 so far, no matter failures)

**Comment by oxddr** [comment]
`pull-perf-tests-verify-dashboard` has passed just fine.

**Pull request merged**
