### PR TITLE
Bunch of cl2 no-op cleanups

### PR DESCRIPTION
**Pull request by mm4tt**

### CODE REVIEW

**Comment by mm4tt** [comment]
Not so no-op it seems :)

**Comment by mm4tt** [comment]
Actually looks like a gcp issue: 
```
W1214 11:53:47.394] 2020/12/14 11:53:47 process.go:153: Running: gcloud compute --project=k8s-presubmit-scale-21 project-info describe
W1214 11:53:48.377] ERROR: (gcloud.compute.project-info.describe) Could not fetch resource:
W1214 11:53:48.379]  - Internal Error
```

**Comment by tosi3k** [comment]
> Actually looks like a gcp issue

Looks like a big outage at Google...

**Pull request merged**
