### PR TITLE
ClusterLoader: upgrade to k8s 1.18

### PR DESCRIPTION
**Pull request by coltonstapper**
Upgrade Go to 1.13
Set context for all requests
Update tests
Update vendor

### CODE REVIEW

**Comment by wojtek-t** [comment]
@coltonstapper - sorry, I missed that PR.

Currently the failures seem relevant, e.g. this one:
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/perf-tests/1187/pull-perf-tests-clusterloader2/1257461843572559872/build-log.txt
This doesn't compile.

Please fix.

**Comment by coltonstapper** [comment]
@wojtek-t you're right I did a bad rebase and missed a newly added client-go call, should be fixed now!

**Comment by coltonstapper** [comment]
`verify/test.sh
can't load package: package k8s.io/perf-tests/benchmark/pkg/comparer/schemes: cannot find package "k8s.io/perf-tests/benchmark/pkg/comparer/schemes" in any of:`
^ that's interesting : 🤔

**Comment by wojtek-t** [comment]
Please ignore the verify-all script, it's broken. We will fix it.
If the clusterloader2 will pass, it will be enough.

**Pull request merged**
