### PR TITLE
ClusterLoader - Moving common/simple/ content to common/

### LINKED ISSUE #642: Move all contents of clusterloader2/pkg/measurement/common/simple/ down to common/
/assign @krzysied

### PR DESCRIPTION
**Pull request by krzysied**
/fixes #642

### CODE REVIEW

**Comment by mm4tt** [comment]
/assing @oxddr 

Janek said he had some pending PRs in this directory, so moving it may currently create more harm than gain :)

**Comment by wojtek-t** [comment]
> Janek said he had some pending PRs in this directory, so moving it may currently create more harm than gain :)

I'm fine with waiting couple days, but there will always be open PRs against it.
And note that if you move them via git mv - git rebase just picks it, so it shouldn't add much more pain.

**Comment by oxddr** [comment]
Thanks for the cleanup 

However let me cleanup backlog of PR touching this directory and then merge this PR, so 
/hold

**Pull request merged**
