### PR TITLE
Make prometheus monitor etcd on 2379 or 2382 port.

### PR DESCRIPTION
**Pull request by mm4tt**
Ref. https://github.com/kubernetes/kubernetes/pull/77561

### CODE REVIEW

**Comment by wojtek-t** [comment]
LGTM once tests are passing - please fix :)

**Comment by mm4tt** [comment]
> LGTM once tests are passing - please fix :)

Ehhh, done :)

**Comment by wojtek-t** [comment]
Still failing.

**Comment by mm4tt** [comment]
Third time's a charm, PTAL :)

**Pull request merged**
