### PR TITLE
Create StatefulSets in load test

### PR DESCRIPTION
**Pull request by mm4tt**
Ref. https://github.com/kubernetes/perf-tests/issues/704

### CODE REVIEW

**Comment by wojtek-t** [comment]
/lgtm

/hold
Please check when the runs finish if those StatefulSets were really created in presubmits. If so, feel free to cancel.

**Comment by mm4tt** [comment]
/hold cancel

Looks good, in both test I found

```
...
W0904 13:24:08.852] I0904 13:24:08.851404   12832 wait_for_pods.go:86] WaitForControlledPodsRunning: namespace(test-ke9lti-1), labelSelector(name=medium-statefulset-0): Pods: 30 out of 30 created, 30 running, 0 pending scheduled, 0 not scheduled, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady 
W0904 13:24:08.929] I0904 13:24:08.929349   12832 wait_for_controlled_pods.go:211] WaitForControlledPodsRunning: running 2, deleted 0, timeout: 0, unknown: 0
W0904 13:24:08.930] I0904 13:24:08.929410   12832 wait_for_controlled_pods.go:225] WaitForControlledPodsRunning: 2/2 StatefulSets are running with all pods
...
```

**Pull request merged**
