### PR TITLE
[WIP] Decrease anet scrape interval to 15s

### PR DESCRIPTION
**Pull request by Weil0ng**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by wojtek-t** [comment]
/assign @marseel @mborsz @jprzychodzen 

There were reasons why this was set so high, so I'm not sure we can just lower this down.

[Also - if we decide to proceed with it, please first merge to master and only then backport.]

**Comment by Weil0ng** [comment]
> Hi, sorry for long delay. I was wondering how many pods are you trying to scrape?
> If I remember correctly, 10m interval was tested with ~37k pods and a few metrics were exposed from each pod.

Hi, I tried this PR with up to 2k nodes/60k pods, it'll cause prometheus OOM in 5k node/150k pods test...

**Comment by marseel** [comment]
You can find cpu/memory limits for prometheus here: https://github.com/kubernetes/perf-tests/blob/master/clusterloader2/pkg/prometheus/manifests/prometheus-prometheus.yaml#L19

I would suggest giving a lot of resources for prometheus and checking how much it consumed during test execution. Also, it's worth to double check that all targets where scraped (for example if we are not lacking cpu too).

**Comment by Weil0ng** [comment]
Thanks! I think at this point we are not dependent on fine-grained anet metrics as we were, let's leave this PR open in case we need to run with a modified interval. In the short term, we can decide either:
- close this PR directly without lowering the scrape interval if there's no compelling need from the tests
- find a proper interval that we can afford and adjust prom requests along with it (as you suggested)

**Comment by marseel** [comment]
Sounds good ;)

**Comment by marseel** [comment]
In case you need me to look at this PR, just assign it back to me.
/unassign @marseel

**Comment by Weil0ng** [comment]
Seems like we no longer need anet metrics at this granularity for experiments, closing this PR, will reopen if needs resurface, thanks for all the feedbacks :)

**Pull request closed without merging**
