### PR TITLE
Make Prometheus work in kubemark clusters.

### PR DESCRIPTION
**Pull request by mm4tt**
Ref https://github.com/kubernetes/kubernetes/issues/74213

### CODE REVIEW

**Comment by mm4tt** [comment]
Something is wrong with author of my commit and the cla check fails, will resend

**Comment by krzysied** [comment]
> Something is wrong with author of my commit and the cla check fails

@mm4tt It could happen when you are pushing changes from another device and you haven't properly configured github account.
Sometimes it happens without any reason ¯\_(ツ)_/¯ - push with -f flag helps.

**Pull request closed without merging**
