### PR TITLE
[dns/py] Major improvements on dns perf tests

### PR DESCRIPTION
**Pull request by migueleliasweb**
A superset of changes from #100 .

In order to make the DNS perf tests work I had to change quite a bit o code that's why the "full PR" was broken into two.

This PR adds:

- Improved error reporting on boilerplate verification
- Integrated reporting with reporting.py (dns/py/report.py)
- Dockerfile for running python script for dns-perf

### CODE REVIEW

**Comment by bowei** [comment]
Can you avoid changing the indentation and whitespace changes? I'm seeing a lot of lines changed due to this.

**Comment by migueleliasweb** [comment]
@bowei Sure ! Should I create a separate PR for this or should I just forget it ?

**Comment by bowei** [comment]
I would prefer to not reindent the files as that obscures git history without much benefit, unless the code is currently in an inconsistent state.

**Comment by migueleliasweb** [comment]
@bowei Basically what happened is that I ended up changing quite a bit o stuff. Sadly the code for the dnsperf from the master branch is not working at all, as seen from my description on #100 .

If you don't mind the amount of lines changed, it would be very interesting to see this PR's code on the master branch since this fixes the whole dns perf test and also adds some interesting features to the module.

The identation althought not essencial, helps the code to be in sync with the PEP8. Once again, not critical but a good practice.

If the identation is a major problem, have a look at this other PR with way less changes due to the PEP8.

See: #103

**Pull request closed without merging**
