### PR TITLE
WIP - Add a measurement for DNS programming latency.

### PR DESCRIPTION
**Pull request by oxddr**

### CODE REVIEW

**Comment by wojtek-t** [comment]
@oxddr - is this ready for review? Or you're still experimenting with it?

**Comment by oxddr** [comment]
I've created a PR from the code I on my machines, so it doesn't get lost.

This piece was written a while back, so I need to double check it. I'll
ping you once I'm ready for a review.

**Comment by mm4tt** [comment]
Ref. https://github.com/kubernetes/perf-tests/issues/617

Let's close it, the code won't disappear. We can take a look at it and see if something can scavenged from this PR when we'll be working on https://github.com/kubernetes/perf-tests/issues/617

**Pull request closed without merging**
