### PR TITLE
Update go version & Minor fixes to unblock dependencies upgrade

### PR DESCRIPTION
**Pull request by wojtek-t**
#### Which issue(s) this PR fixes:

Fixes #

### CODE REVIEW

**Comment by wojtek-t** [comment]
Blocked on https://github.com/kubernetes/test-infra/pull/32772

**Comment by tosi3k** [comment]
Would it make sense to squash the commits or do you prefer to have it the current way?

If latter, then feel free to unhold (treat my nits as non-blocking).

/lgtm
/hold

**Comment by wojtek-t** [comment]
Leaving as is, in case we will need to revert some part.

/hold cancel

**Pull request merged**
