### PR TITLE
Add an option to inject additional measurements to load config

### PR DESCRIPTION
**Pull request by Argh4k**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

This PR allows to inject additional measurements via CL2_ADDITIONAL_MEASURMENT_MODULES to load/config.yaml.

#### Which issue(s) this PR fixes:
Fixes #

### CODE REVIEW

**Comment by Argh4k** [comment]
It looks like tests failures are unrelated to my change as clusterloader is not able to ssh on to  the master:
```
error getting SSH client to prow@34.23.203.237:22: 'ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```

**Comment by Argh4k** [comment]
Tests are failing with:
```
ERROR: (gcloud.compute.instances.create) Could not fetch resource:
 - Quota 'N2_CPUS' exceeded.  Limit: 24.0 in region us-east1.
	metric name = compute.googleapis.com/n2_cpus
	limit name = N2-CPUS-per-project-region
	limit = 24.0
	dimensions = region: us-east1
```

**Comment by Argh4k** [comment]
https://github.com/kubernetes/test-infra/pull/31546 

I will raise this in sig-testing slack channel.

**Comment by Argh4k** [comment]
FYI https://kubernetes.slack.com/archives/C09QZ4DQB/p1704722468347639

**Comment by dlapcevic** [comment]
Thanks @Argh4k for looking into the test failures.
I have the same cl2 test failures in my PR https://github.com/kubernetes/perf-tests/pull/2494.

I see that the quota increase for N2 machines is in progress.
Is it tracked somewhere?

**Comment by Argh4k** [comment]
@dlapcevic unfortunately all the information that I have are from the slack thread that I posted here :(

**Comment by Argh4k** [comment]
@mborsz can we push it through? Clusterloader2 test is failing with N2 quota issue and clusterloader2-kubemark is failing with:
```
ERROR: (gcloud.compute.instances.create) Could not fetch resource:
 - Setting minimum CPU platform is not supported for the selected machine type e2-standard-8.
 ```
They do not seem to be connected to my CL.

For testing I've set up a simple test with measurments in file one directory above and run the clusterloader with that. I'm attaching files and generatedConfig for that (they are formatted as txt but in reality those are yamls as github does not allow to attach yamls in the comment)

[generatedConfig_test.txt](https://github.com/kubernetes/perf-tests/files/13902054/generatedConfig_test.txt)
[measurements.txt](https://github.com/kubernetes/perf-tests/files/13902055/measurements.txt)
[config.txt](https://github.com/kubernetes/perf-tests/files/13902056/config.txt)

**Comment by marseel** [comment]
FYI https://github.com/kubernetes/k8s.io/issues/6271

**Pull request merged**
