### PR TITLE
Enable Google Anet scraping

### PR DESCRIPTION
**Pull request by Weil0ng**
Signed-off-by: Weilong Cui <cuiwl@google.com>

**What type of PR is this?**
backport of PR #1682 

**What this PR does / why we need it**:
Needed for scarping metrics for Google scalability job.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by tosi3k** [comment]
Assigning @mm4tt as I don't have permissions to approve the PR.

/assign @mm4tt

**Comment by wojtek-t** [comment]
@Weil0ng @tosi3k - can we please merge that first to 1.20 and 1.19? Having this just in master and 1.18 seems wrong.

**Comment by Weil0ng** [comment]
> @Weil0ng @tosi3k - can we please merge that first to 1.20 and 1.19? Having this just in master and 1.18 seems wrong.

Done, PTAL https://github.com/kubernetes/perf-tests/pull/1702 and https://github.com/kubernetes/perf-tests/pull/1703

**Pull request merged**
