### PR TITLE
Feature gate to enable N/w Programming Latencies SLO measurement for …

### PR DESCRIPTION
**Pull request by hakuna-matatah**
…Load tests

#### What this PR does / why we need it:

This PR gives the ability to measure/validate Network Programming Latencies SLOs for cloudproviders during CL2 load test when enabled. 
It's backwards compatible, it defaults to feature being disabled.

#### Which issue(s) this PR fixes:

Fixes #
https://github.com/kubernetes/perf-tests/issues/2407

### CODE REVIEW

**Comment by hakuna-matatah** [comment]
@wojtek-t  If you remember, I have discussed this with you in sig-scalability meeting couple weeks back, ability to measure this networking SLOs when enabled.
Please let me know if you have any questions.

**Comment by wojtek-t** [comment]
/lgtm
/approve

This will not merge until we fix log-dumping for scalability jobs though...

**Pull request merged**
