### PR TITLE
clusterloader2: completely switch to secure port

### PR DESCRIPTION
**Pull request by knight42**
**What type of PR is this?**

/kind cleanup
/kind deprecation

**What this PR does / why we need it**:

Now both [controller-manager](https://github.com/kubernetes/kubernetes/pull/96216) and [scheduler](https://github.com/kubernetes/kubernetes/pull/96345) are migrating off the insecure port, and the progress is being blocked by the job `pull-kubernetes-e2e-gce-100-performance`, because `clusterloader2` in this job would fetch metrics from the insecure port of scheduler.

This PR picks up @ingvagabund 's great work #1562, and make `clusterloader2` no longer depend on the insecure port of controller-manager and scheduler.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
clusterloader2: grab metrics from the secure port of kube-controller-manager and kube-scheduler
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by wojtek-t** [comment]
/assign @tosi3k @marseel 

@tosi3k @marseel - Can you please verify that we have all metrics we want (i.e. this works as expected)?

**Comment by ingvagabund** [comment]
@knight42 you can drop `WIP: ` bit from the first commit message

Is this really sufficient? :)

**Comment by ingvagabund** [comment]
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/perf-tests/1647/pull-perf-tests-clusterloader2/1347043219300421632/artifacts/SchedulingMetrics_load_2021-01-07T05:16:52Z.json looks good

From https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/perf-tests/1647/pull-perf-tests-clusterloader2/1347043219300421632/build-log.txt:

```
W0107 05:00:24.464] I0107 05:00:24.464530   15135 framework.go:239] Applying /go/src/k8s.io/perf-tests/clusterloader2/pkg/prometheus/manifests/master-ip/master-endpoints.yaml
W0107 05:00:24.501] I0107 05:00:24.501108   15135 framework.go:239] Applying /go/src/k8s.io/perf-tests/clusterloader2/pkg/prometheus/manifests/master-ip/master-service.yaml
W0107 05:00:24.540] I0107 05:00:24.539715   15135 framework.go:239] Applying /go/src/k8s.io/perf-tests/clusterloader2/pkg/prometheus/manifests/master-ip/master-serviceMonitor.yaml
W0107 05:00:24.577] I0107 05:00:24.577648   15135 prometheus.go:320] Waiting for Prometheus stack to become healthy...
W0107 05:00:54.614] W0107 05:00:54.613997   15135 util.go:64] error while calling prometheus api: the server is currently unable to handle the request (get services http:prometheus-k8s:9090), response: "k8s\x00\n\f\n\x02v1\x12\x06Status\x12]\n\x06\n\x00\x12\x00\x1a\x00\x12\aFailure\x1a3no endpoints available for service \"prometheus-k8s\"\"\x12ServiceUnavailable0\xf7\x03\x1a\x00\"\x00"
W0107 05:01:24.720] I0107 05:01:24.719797   15135 util.go:93] 97/116 targets are ready, example not ready target: {map[endpoint:http-metrics instance:10.40.0.37:10249 job:kube-proxy namespace:kube-system pod:kube-proxy-e2e-1647-62db2-minion-group-9l8j service:kube-proxy] unknown}
W0107 05:01:54.683] I0107 05:01:54.683511   15135 util.go:96] All 116 expected targets are ready
W0107 05:01:54.764] I0107 05:01:54.764602   15135 util.go:96] All 1 expected targets are ready
W0107 05:01:54.765] I0107 05:01:54.764660   15135 prometheus.go:199] Prometheus stack set up successfully
```

Interesting :) How did you manage to get the authentication/authorization working?

**Comment by knight42** [comment]
>  How did you manage to get the authentication/authorization working?

@ingvagabund because the flags `--authentication-kubeconfig` and `--authorization-kubeconfig` are set now: https://github.com/kubernetes/kubernetes/pull/96550

**Comment by ingvagabund** [comment]
Awesome!!! I did not check that PR yet. Well done :)

**Comment by tosi3k** [comment]
> @tosi3k @marseel - Can you please verify that we have all metrics we want (i.e. this works as expected)?

Sorry, I was OOO yesterday. I'll take a look at this later today.

**Comment by wojtek-t** [comment]
Nice - thanks!

/approve

**Pull request merged**
