### PR TITLE
Dependency nightmare

### PR DESCRIPTION
**Pull request by sjug**
All this to try and make [Travis happy](https://github.com/kubernetes/perf-tests/issues/26).

### CODE REVIEW

**Comment by sjug** [comment]
@gmarek this is as good as it's going to get. If you want Travis to pass recursive go test, then you'll have to ask https://github.com/kubernetes/kubernetes how they did it.

**Comment by gmarek** [comment]
They did it by flattening the repos (as @timothysc tool should have done).

```
clusterloader/vendor/k8s.io/client-go/rest/request.go:21:2: cannot find package "context" in any of:
	/home/travis/gopath/src/k8s.io/perf-tests/clusterloader/vendor/context (vendor tree)
	/home/travis/.gimme/versions/go1.6.linux.amd64/src/context (from $GOROOT)
	/home/travis/gopath/src/context (from $GOPATH)
```

**Comment by sjug** [comment]
Which tool is that?

**Comment by timothysc** [comment]
@sjug this isn't godep, this is the main repo doing unholy "staging" things that absolutely 0 projects do.  As a result there needs to be some script hackery to bypass.  My script flattens the dep-chain.

**Comment by sjug** [comment]
@timothysc what/where is your script?

**Comment by timothysc** [comment]
In your repo you are trying to update: 

``` 
rm -rf Godeps vendor
export KPATH=$GOPATH/src/k8s.io/kubernetes
export GOPATH=$GOPATH:$KPATH/staging

$KPATH/hack/generate-bindata.sh
godep save ./...
cp -L -R $KPATH/vendor/k8s.io/api* $KPATH/vendor/k8s.io/client-go ./vendor/k8s.io/
cp $KPATH/test/e2e/generated/bindata.go ./vendor/k8s.io/kubernetes/test/e2e/generated/bindata.go
```

**Comment by sjug** [comment]
@timothysc I ran all that to generate this PR, of course.

**Comment by wojtek-t** [comment]
@gmarek @sjug - so what is the reason behind having a separate "vendor" directory under clusterloader/ ?
Why can't we have just a single top-level vendor/ directory?

**Comment by gmarek** [comment]
We tried that in contrib, and it doesn't work. Imagine that you have an old *thing* that uses version X of something. Then you write a *another thing* which uses version X+1 of the same something. If you have a single vendor it's just pain and tears (even more than having separate ones).

**Comment by wojtek-t** [comment]
I see - thanks.

That said, it's clear that something is still missing in this PR. It seems that the code doesn't see the golang "context" package at all.

**Comment by sjug** [comment]
I don't understand the purpose of running `go get` and `go test` on vendor.

I have used @timothysc commands to create vendor and this is the end result. How is it possible that it is unable to find a built-in package?

**Comment by wojtek-t** [comment]
@sjug - I never knew how to use godeps. so I'm not really able to help with this problem.

**Comment by gmarek** [comment]
I copied it from somewhere, but I agree - no point of running `go get/test` on vendor. Feel free to send a PR that skips them.

**Comment by sjug** [comment]
@gmarek Funnily enough Travis is now failing on the same issue with other packages. Did you want me to fix them in this PR or leave it for the original author?

**Comment by wojtek-t** [comment]
I'm fine with merging this as is, though if you could fix them in a separate PR it would be awesome (so that we have passing travis).

**Comment by sjug** [comment]
@wojtek-t If we bring up golang from 1.6 then I won't need the last commit fix, nor will the other package so that works too :smile:

**Comment by wojtek-t** [comment]
@gmarek - it seems that after bumping to Go 1.7 it is worse, a bunch of other things doesn't compile, e.g.:

# k8s.io/perf-tests/clusterloader/vendor/github.com/Microsoft/go-winio
clusterloader/vendor/github.com/Microsoft/go-winio/file.go:45: undefined: syscall.Overlapped

**Comment by gmarek** [comment]
The same thing broke in the benchmark. I'm kind of curious what this packet actually is...

**Comment by shyamjvs** [comment]
Even in general, it might be a good practice (not 100% sure) to check just if all dependency packages are downloadable when we are running go get. Whether the tools inside the repo actually compile is a headache that we should delegate to the makefiles inside those repos.

**Comment by sjug** [comment]
So for the missing packages according to `go test`:
"github.com/elazarl/goproxy"
"github.com/stretchr/testify/assert"

These are not pulled in by `godep`, should I add them manually to vendor?

**Comment by shyamjvs** [comment]
@sjug Not sure if I understand it totally, but something's wrong if you're needing to vendor manually. Because this would mean godep failed to identify those dependencies during `godep save ./...`.

**Comment by wojtek-t** [comment]
@sjug - we are finally at the state where the errors seem reasonable:
```
# k8s.io/perf-tests/clusterloader
clusterloader/cluster_loader.go:78: cannot use f (type *"k8s.io/perf-tests/clusterloader/vendor/k8s.io/kubernetes/test/e2e/framework".Framework) as type *"github.com/kubernetes/perf-tests/clusterloader/vendor/k8s.io/kubernetes/test/e2e/framework".Framework in argument to "github.com/kubernetes/perf-tests/clusterloader/framework".CreatePods
clusterloader/cluster_loader.go:78: cannot use config.Spec (type "k8s.io/perf-tests/clusterloader/vendor/k8s.io/kubernetes/pkg/api/v1".PodSpec) as type "github.com/kubernetes/perf-tests/clusterloader/vendor/k8s.io/kubernetes/pkg/api/v1".PodSpec in argument to "github.com/kubernetes/perf-tests/clusterloader/framework".CreatePods
```

Can you please take a look why we have those?

**Comment by sjug** [comment]
Taking a look at this, it's very strange because I don't get any errors building at all?

**Comment by wojtek-t** [comment]
> Why does the error message lead with # k8s.io/perf-tests/clusterloader? That's not the path... 

Sorry, I don't udnerstand. The repo is k8s.io/perf-tests, main directory is clusterloader, so it seems that it is the path.

> Are you guys able to reproduce it locally?

Didn't try to patch your PR and I'm afraid I won't have time to patch it in the next few days.

**Comment by wojtek-t** [comment]
OK I'm going to merge this now, since the state with this PR is better than without it.

But we should fix this ASAP.
@sjug - will be able to look into it?

**Comment by shyamjvs** [comment]
So I tried running `godep restore` with this change and followed it up with a `godep save ./...` to check the integrity of the migration. And the save failed with the following:
```
godep: Package (github.com/aws/aws-sdk-go/private/endpoints) not found
```

I guess something's wrong with the way godeps have been created. Besides I created godeps from glide deps with the wrong paths fixed last week (https://github.com/shyamjvs/perf-tests/commit/fcba424962cad452c96a7ac3c4afd1b7cfba1df7) and the size of my `/vendor` dir was 17MB smaller. Did you do any manual tweaking with the godep @sjug ?

**Comment by sjug** [comment]
@wojtek-t but the path is set to `github.com/perf-tests/clusterloader`?

@shyamjvs I don't think it's simply restorable as vendoring in k8s is not that simple, I had to use this script https://github.com/kubernetes/perf-tests/pull/40#issuecomment-297142963

**Comment by wojtek-t** [comment]
> @wojtek-t but the path is set to github.com/perf-tests/clusterloader?

As I wrote somewhere already, I don't understand godeps. But we are refering to all k8s repos as:
k8s.io/<repo>/<dir> and changing it here fixed the problem. And it works now, while it didn't work (also for me locally) before.

**Pull request merged**
