### PR TITLE
Migrate network/perf to go modules

### PR DESCRIPTION
**Pull request by sknat**
It migrates `network/performance` to go modules ( so fixes a part of #1099 )
It also adds a way to specify pull policy for locally built images

### CODE REVIEW

**Comment by oxddr** [comment]
Hi @sknat, please sign CLA (detailed instructions appear when you click "Details").

**Comment by sknat** [comment]
Hi @oxddr , sorry for the delayed response 
I missed the timeout for signing the CNCF individual contributor CLA the first time, and I've been unable to re-trigger the email since, nor emailing support through the interface.
Any idea who can help me on this one ?
Thanks in advance

**Comment by sknat** [comment]
I signed it

**Comment by mm4tt** [comment]
The CI bot doesn't see it as signed. If you indeed signed, trying closing this PR and opening a new one.

BTW, please move the "imagePullPolicy" flag changes to a separate PR

**Pull request closed without merging**
