### PR TITLE
Backport scheduling throughput to 1.18

### PR DESCRIPTION
**Pull request by marseel**
Cherry-pick: #1093 

* Add measurmentInterval parameter to SchedulingThroughput
* SchedulingThroughput threshold compares to max value, instead of 99th
  percentile
* Remove broken average value

**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by mborsz** [comment]
Please backport to 1.19 first

**Comment by marseel** [comment]
1.19 was already backported by @jprzychodzen

**Comment by marseel** [comment]
Actually this changed was merged to master before 1.19 was released ;)

**Comment by mborsz** [comment]
:)
/ok-to-test
/lgtm
/approve

**Pull request merged**
