### PR TITLE
Updated go.mod with version 0.22.15

### PR DESCRIPTION
**Pull request by Ganiredi**
**What type of PR is this?**
Changed the go.mod client go version with v0.22.15 and able to build the binary.

**What this PR does / why we need it**:

k8s Cl2 using v0.20.12 and we are trying to test against the version k8s 1.22 and 1.23 which is getting failed throws us invalid apiversion error,after the version upgrading every test is getting  passed with the versions that were updated in go.mod

Its new PR after changing the patch versions https://github.com/kubernetes/perf-tests/pull/2161

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by mborsz** [comment]
/lgtm
/approve
Thanks!

**Comment by mborsz** [comment]
Now our internal tests are passing. Updating from 0.22.3 to 0.22.15 solved the issue.

**Comment by Ganiredi** [comment]
@mborsz Good to hear ,Thanks!!

**Pull request merged**
