### PR TITLE
[NodeKiller] Schedule reboot and disconnect from node v2

### PR DESCRIPTION
**Pull request by jprzychodzen**
Second version of a Node Killer reboot and disconnect

Ref. kubernetes/kubernetes#89051

/sig scalability
/assign @mm4tt

### CODE REVIEW

**Comment by jprzychodzen** [comment]
Checked if nodes are rebooted. They are.

**Comment by jprzychodzen** [comment]
/retest

Checking if very flaky.

**Comment by jprzychodzen** [comment]
Moved density config change to #1148

**Comment by jprzychodzen** [comment]
/hold

Until #1148 is merged

**Comment by mm4tt** [comment]
Let's close as discussed in https://github.com/kubernetes/perf-tests/pull/1148
/close

**Pull request closed without merging**
