### PR TITLE
WIP: Update master-ip flags and vars to plural

### LINKED ISSUE #595: ClusterLoader2 - update (internal-)?master-ip flags and vars to plural
Multi-master support was added to ClusterLoader2 in https://github.com/kubernetes/perf-tests/pull/544.

We should update the name of master-ip and internal-master-ip flags and vars to plural.

### PR DESCRIPTION
**Pull request by Jukie**
Fixes #595 

**Dependent on https://github.com/kubernetes/test-infra/pull/14613, do not merge yet**

### CODE REVIEW

**Comment by Jukie** [comment]
Should I also cleanup https://github.com/kubernetes/perf-tests/blob/7d8c6a23b77782c1f5d7a550c3e04f8cf03fa38b/clusterloader2/pkg/config/cluster.go#L55-L69?

**Comment by alejandrox1** [comment]
> > Should I also cleanup these to be plural?
> > https://github.com/kubernetes/perf-tests/blob/7d8c6a23b77782c1f5d7a550c3e04f8cf03fa38b/clusterloader2/pkg/config/cluster.go#L55-L69
> 
> Let's leave it as is for now. I think @alejandrox1 is working on that.

Already have this in progress here https://github.com/kubernetes/perf-tests/pull/833

**Pull request closed without merging**
