### PR TITLE
Fix the port number to collect the profiling data for the apiserver

### PR DESCRIPTION
**Pull request by chendave**
`443` is the tcp port for the cluster ip `10.96.0.1`, which is used by
service `kubernetes`.

Connect the port with the localhost and fetch the profiling data is not allowed,

> curl -k https://localhost:443/debug/pprof/profile?seconds=30 -o cpu2.pprof

>  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to localhost port 443: Connection refused

Because of this, profiling file for apiserver is always empty,

> file 10.253.2.51_kube-apiserver_CPUProfile_load_2021-08-26T11:10:26Z.pprof
10.253.2.51_kube-apiserver_CPUProfile_load_2021-08-26T11:10:26Z.pprof: empty

We should either update the url to use clusterip:443 or just update the port
to use the port exposed by the pod directly.

Signed-off-by: Dave Chen <dave.chen@arm.com>

**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
Actually,  I am not pretty sure is this a bug or just something I missed, the original code has been last for one year, why no one report the issue?

 
**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by MikeSpreitzer** [comment]
My experience with #1928 -> #1930 might be relevant here.

**Comment by chendave** [comment]
@MikeSpreitzer thanks Mike!

> My experience with #1928 -> #1930 might be relevant here.

I took a glance at that one, and I believe #1931 is relevant but we still fix this one separately. As they are belonging to different code path and for different purpose.

I was trying to collect `pprof` data for cpu and memory, and the port is hard coded here, 
https://github.com/kubernetes/perf-tests/blob/ef1ad81804b668626478375c794b9fa08031fc32/clusterloader2/pkg/provider/util.go#L25-L37

and is called by, 

https://github.com/kubernetes/perf-tests/blob/ef1ad81804b668626478375c794b9fa08031fc32/clusterloader2/pkg/measurement/common/profile.go#L228-L244


this pr is the easiest way to fix it, also as I said in the commit message, I am not sure why the code stands here for such a long time without any complaint.


@wojtek-t @mm4tt  could you pls take a look?  I not sure who are the most active reviewers at the moment, sorry if I ping the wrong person.

**Comment by MikeSpreitzer** [comment]
@chendave : My point is that I could not find one port number that is always the right one to use for reaching the kube-apiserver.

**Comment by MikeSpreitzer** [comment]
@chendave : what I am trying to suggest is that you make that port number a parameter.
/remove-lifecycle stale

**Comment by chendave** [comment]
@MikeSpreitzer Got your point, will update ASAP, thanks!

**Comment by chendave** [comment]
I think all the ports there should be better to configurable, this pr only focus on apiserver port since only the apiserver is an issue in my env. 

https://github.com/kubernetes/perf-tests/blob/30041333d995b8d3008bfaeeea594dfaae157be4/clusterloader2/pkg/provider/util.go#L25-L37

**Comment by chendave** [comment]
@MikeSpreitzer WDYT?

**Pull request closed without merging**
