### PR TITLE
Enable secrets and configmaps in load test

### PR DESCRIPTION
**Pull request by mm4tt**
This also merges experimental load with the real load test.

The "knob" has been enabled in presubmits in https://github.com/kubernetes/test-infra/pull/14166.

Ref. https://github.com/kubernetes/perf-tests/issues/704

### CODE REVIEW

**Comment by wojtek-t** [comment]
I'm not sure if this was a flake - e.g. these logs from hollow-kubelet:
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/perf-tests/767/pull-perf-tests-clusterloader2-kubemark/1168528796492500992/artifacts/e2e-767-0bf8a-minion-group-hghw/kubelet-hollow-node-dp47t.log

**Comment by wojtek-t** [comment]
https://github.com/kubernetes/kubernetes/pull/82259 should fix the problem once merged

**Comment by wojtek-t** [comment]
/lgtm cancel

@mm4tt - please change start setting configmaps/secrets in deployment.yaml now

**Comment by mm4tt** [comment]
> /lgtm cancel
> 
> Matt Matejczyk - please change start setting configmaps/secrets in deployment.yaml now

Done.

**Pull request merged**
