### PR TITLE
[cherry pick 1.17] scheduler-suite: pod-affinity, pod-anti-affinity, pod-topology-spread

### PR DESCRIPTION
**Pull request by adtac**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**: This PR cherry picks the recent scheduler-suite additions to 1.17.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

/cc @tosi3k

### CODE REVIEW

**Comment by tosi3k** [comment]
Weird that cl2 presubmits were shot in a PR to a non-master branch...

/lgtm
/assign @wojtek-t

**Comment by adtac** [comment]
cc @ahg-g

**Comment by ahg-g** [comment]
@adtac can you make sure that the tests are not just flakes?

**Comment by mborsz** [comment]
I think all tests are failing. It's unlikely it's a flake. Can you take a look?

**Comment by adtac** [comment]
tests passing again after I amended + force-pushed -- I'm not really sure what triggered the other tests last time

**Comment by adtac** [comment]
ping @mborsz

**Comment by adtac** [comment]
ping @marseel :)

**Comment by mborsz** [comment]
/lgtm
/approve

Sorry, I missed this PR. In future feel free to ping me on chat if you are waiting for review.

**Pull request merged**
