### PR TITLE
Feat/Update Prometheus manifests

### LINKED ISSUE #2035: Prometheus support for Azure
**What would you like to be added**:
- Windows Exporter as a HostProcess container

- Node Exporter as a daemonset

- Add Azure-Disk drivers

- Update ssd storageClass to support azure-disk configuration

**Why is this needed**:

Currently GCloud SSH is being used to install WMI exporter on Windows nodes and to provision the node-exporter manifest on the master nodes.

part of https://github.com/kubernetes/kubernetes/issues/108621

### PR DESCRIPTION
**Pull request by oprinmarius**
**What type of PR is this?**
/kind feature
/kind design

**What this PR does / why we need it**:
- Add node-exporter as a daemonset
- Add Windows Exporter as a HostProcess container
- Add Azure-Disk drivers
- Add support for Azure-Disk StorageClass

**Which issue(s) this PR fixes**:
Fixes #2035

**Special notes for your reviewer**:
part of https://github.com/kubernetes/kubernetes/issues/108621
blocking https://github.com/kubernetes/perf-tests/pull/2034

**Does this PR introduce a user-facing change?**:

```release-note
- Add support for Prometheus deployments in Azure
- Add support for Azure-Disk StorageClass
- Windows Exporter as a HostProcess container
- Node Exporter as a deamonset
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by mborsz** [comment]
Thanks for the PR!

It looks like this PR is trying to do few separated things: implement CSI for Azure, upgrade prometheus, add node-exporter, etc..

Could you split the PR into few smaller ones that we can review those changes one by one?

**Comment by oprinmarius** [comment]
> Thanks for the PR!
> 
> It looks like this PR is trying to do few separated things: implement CSI for Azure, upgrade prometheus, add node-exporter, etc..
> 
> Could you split the PR into few smaller ones that we can review those changes one by one?

Sure, I opened the following PRs:
https://github.com/kubernetes/perf-tests/pull/2040
https://github.com/kubernetes/perf-tests/pull/2041
https://github.com/kubernetes/perf-tests/pull/2042

**Comment by oprinmarius** [comment]
Going to close this PR since I opened smaller PRs containing these changes

**Pull request closed without merging**
