### PR TITLE
Fix a few spelling mistakes.

### PR DESCRIPTION
**Pull request by Sakuralbj**
Fix several spelling mistakes in clusterloader2/pkg/measurement/util

### CODE REVIEW

**Comment by mm4tt** [comment]
Thanks!

Please sign the CLA as otherwise it wouldn't be possible to merge this PR

**Comment by Sakuralbj** [comment]
@mm4tt  Thank you.I have signed it.

**Comment by mm4tt** [comment]
/ok-to-test
/lgtm
/approve

Thanks!

**Pull request merged**
