### PR TITLE
Migrate to master and non-daemons mode (1.18)

### PR DESCRIPTION
**Pull request by jkaniuk**
Cherry-pick: #1279

Ref #1275

/cc @wojtek-t, @mborsz

### CODE REVIEW

**Comment by wojtek-t** [comment]
/lgtm
/approve

@jkaniuk @jprzychodzen - why presubmits aren't firing on release branches?

**Comment by jprzychodzen** [comment]
> why presubmits aren't firing on release branches?

It seems reverted in kubernetes/test-infra#16360. Probably we should try to enable them again. To do this we need to book a support of someone to interfere in a case of a broken configuration.

**Comment by jkaniuk** [comment]
> @jkaniuk @jprzychodzen - why presubmits aren't firing on release branches?

I've filed a bug about this but it was deprioritized ;)

**Pull request merged**
