### PR TITLE
Reverting to the state at b31dc7 on release1.15 branch

### PR DESCRIPTION
**Pull request by oxddr**
v1.15.0 tag was added on 14-06-2019, b31dc7 was merged on 12-06-2019.

### CODE REVIEW

**Comment by oxddr** [comment]
ref https://github.com/kubernetes/perf-tests/issues/797

**Comment by mm4tt** [comment]
Have we tested it?

**Comment by oxddr** [comment]
I didn't have time to test those branches yet. I'll let you know once I sort this out.

**Comment by oxddr** [comment]
This branch has been tested against k/h release-1.15. It worked fine.

**Pull request merged**
