### PR TITLE
Add modules for L4 ILB creation latency tests

### PR DESCRIPTION
**Pull request by dlapcevic**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
- Adds modules for measurements and services for L4 ILB tests.
- Modifies the existing service creation latency config.yaml test to use the added modules.
- Modifies service.yaml to receive the value for ExternalTrafficPolicy.
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by tosi3k** [comment]
Could we separate the NPU test config to a different PR? It seems like the modules change is independent of the NPU test config addition as the latter doesn't look as if it's using any modules at the moment.

The division of the original ILB test config into modules looks good to me. As of the NPU test config, I'll review it in a separate PR (feel free to assign me once you create it).

**Comment by tosi3k** [comment]
Thanks for the change. Two last small remarks:
1) let's change the PR's description so it's up to date with its current state,
2) please squash the commits - we usually do one commit per PR as it's easier to revert in case of any unwanted situation after its submission.

**Comment by dlapcevic** [comment]
> Thanks for the change. Two last small remarks:
> 
> 1. let's change the PR's description so it's up to date with its current state,
> 2. please squash the commits - we usually do one commit per PR as it's easier to revert in case of any unwanted situation after its submission.

Done.
Thank you @tosi3k for the review!

**Pull request merged**
