### PR TITLE
Switch to registry.k8s.io

### PR DESCRIPTION
**Pull request by ameukam**
Reference issue:
  - https://github.com/kubernetes/perf-tests/issues/2231

Part of:
  - https://github.com/kubernetes/k8s.io/issues/4738

Signed-off-by: Arnaud Meukam <ameukam@gmail.com>

### CODE REVIEW

**Comment by mborsz** [comment]
/hold

We have had some problems with using registry.k8s.io in testing environments without public internet access.
We need to test this change in such environment before merging or adapt the tests running there to have access to registry.k8s.io.

**Comment by ameukam** [comment]
> testing environments without public internet access.

which environments are talking about ? related to the Kubernetes project ?

**Comment by mborsz** [comment]
The last time this change has broken GKE internal tests (https://github.com/kubernetes/perf-tests/pull/2044) which are using private nodes without internet access. I'm not sure what is a state now and if we expect to registry.k8s.io to work in such cases. I asked the current oncall to investigate this issue.

**Comment by aojea** [comment]
> The last time this change has broken GKE internal tests (#2044) which are using private nodes without internet access. I'm not sure what is a state now and if we expect to registry.k8s.io to work in such cases. I asked the current oncall to investigate this issue.

cc: @BenTheElder

**Comment by BenTheElder** [comment]
So from an OSS perspective, GKE internal test environment issues should really not be blocking upstream changes unless they're surfacing a bug ...

Kubernetes has a merged KEP to cease allowing any new images in GCR for 1.27+, and SIG K8s Infra could choose to shut down GCR even sooner as all images are available at registry.k8s.io and Kubernetes is massively over-budget (think $4M spend rate on $3M GCP budget), primarily due to content download costs.

Kubernetes has been on registry.k8s.io since 1.25, released August '22.

I see the internal bug and will follow-up on GKE's options there.

**Comment by Argh4k** [comment]
Hi, we updated gke internal tests and we are ready to go with this change.

**Comment by ameukam** [comment]
@mborsz @marseel @wojtek-t PTAL.

**Comment by marseel** [comment]
/approve
but waiting for someone from GKE team to unhold when they are ready to merge.

**Comment by aojea** [comment]
as a followup we should update the pause image version, right now kubernetes uses the `3.9` version and this repo seems to be useing `3.1` , I don't know if that can be an issue though

**Comment by vaibhav2107** [comment]
Fixes: #2231

**Pull request merged**
