### PR TITLE
update clusterloader2/vendor for scheduler metrics

### PR DESCRIPTION
**Pull request by RainbowMango**
## Why we need this
The vendor for scheduler metrics is too old.

Please refer to https://github.com/kubernetes/kubernetes/pull/83838#issuecomment-552704198

## How To Do
By command :
`govendor fetch k8s.io/kubernetes/pkg/scheduler/metrics`

### CODE REVIEW

**Comment by RainbowMango** [comment]
@oxddr 
Thanks for your quick response.

I have two questions about the stuff, can you help to clarify?
- Does this will take effect immediately?
- Is there any side effect if we update all packages in the vendor?

**Comment by oxddr** [comment]
1) All scalability test use perf-test repo at HEAD (subject to be change in the nearest future)
2) It depends what you mean specifically as "side-effect". AFAIK there is no other effect of updating vendor than on building scalability tests.

**Comment by RainbowMango** [comment]
Got it. Thanks for your clarification.

Maybe I will send another update later. For PR: https://github.com/kubernetes/kubernetes/pull/83837

**Pull request merged**
