### PR TITLE
Fixed Docker build for networking performance issue: #2067

### LINKED ISSUE #2067: Docker build failing on netpref due to folder name
```
 => ERROR [8/8] COPY nptests /usr/bin/                                                                                                                                                                                              0.0s
------
 > [8/8] COPY nptests /usr/bin/:
------
failed to compute cache key: "/nptests" not found: not found
```
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by sionsmith**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Docker build on Networking benchmarking failing.

**Which issue(s) this PR fixes**:

Fixes #2067

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by sionsmith** [comment]
Hey @m1kola @mm4tt is there anything I need todo in order to get this merged?

**Comment by mm4tt** [comment]
/ok-to-test

/assign @marseel 
/unassign

Assigning to Marcel who is more up2date with what is going on here.

**Comment by sionsmith** [comment]
@mm4tt Is this something you can approve?

**Pull request merged**
